### ISSUE TITLE
Error when copying up to blob storage

### ISSUE THREAD

**Issue by everdeguzman** [Microsoft/AzureStorageExplorer#1013]
I am trying to upload a 3gb file to blob storage and continually get this error after about a minute or two.

```json
{
  "name": "Error",
  "message": "write ECANCELED",
  "stack": "Error: write ECANCELED\n    at _errnoException (util.js:1024:11)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)",
  "code": "ECANCELED",
  "errno": "ECANCELED",
  "syscall": "write",
  "innerError": {
    "code": "ECONNRESET",
    "errno": "ECONNRESET",
    "syscall": "write",
    "innerError": {
      "code": "ECONNRESET",
      "errno": "ECONNRESET",
      "syscall": "write",
      "innerError": {
        "code": "ECONNRESET",
        "errno": "ECONNRESET",
        "syscall": "write",
        "innerError": {
          "code": "ECONNRESET",
          "errno": "ECONNRESET",
          "syscall": "read"
        }
      }
    }
  }
}
```

**Comment by craxal** [comment]
Are you using the Experimental/AzCopy feature? If not, give that a try. It may work better.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of activity.
