### ISSUE TITLE
unable to delete blob storage please help.

### ISSUE THREAD

**Issue by Ravinderhub** [Microsoft/AzureStorageExplorer#1066]
```json
{
  "name": "StorageError",
  "message": "The specified blob does not exist.\nRequestId:c109e9c4-c01e-0135-63d8-ab8395000000\nTime:2019-01-14T07:13:29.4444870Z",
  "stack": "StorageError: The specified blob does not exist.\nRequestId:c109e9c4-c01e-0135-63d8-ab8395000000\nTime:2019-01-14T07:13:29.4444870Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "BlobNotFound",
  "statusCode": 404,
  "requestId": "c109e9c4-c01e-0135-63d8-ab8395000000"
}
```

**Comment by jinglouMSFT** [comment]
The error message indicated that the blob you were trying to delete didn't exist.  Have you tried to verify if you can see the blob from Azure Portal?  Also, any additional info would be helpful.  What were the steps you used to delete?  How did you connect to the storage?  Do you have the delete permission?  Etc. Thanks.
