### ISSUE TITLE
Uploads over 7MB keep failing/timing out.

### ISSUE THREAD

**Issue by julie5566** [Microsoft/AzureStorageExplorer#1094]
```json
{
  "name": "StorageError",
  "message": "The specified blob or block content is invalid.\nRequestId:a6e20757-c01e-00c8-0f3f-b457fa000000\nTime:2019-01-24T23:54:05.6783332Z",
  "stack": "StorageError: The specified blob or block content is invalid.\nRequestId:a6e20757-c01e-00c8-0f3f-b457fa000000\nTime:2019-01-24T23:54:05.6783332Z\n    at Function.StorageServiceClient._normalizeError (/private/var/folders/_y/v50r58vd4897phjb3nrc_7qm0000gp/T/MicrosoftAzureStorageExplorer 2/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (/private/var/folders/_y/v50r58vd4897phjb3nrc_7qm0000gp/T/MicrosoftAzureStorageExplorer 2/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (/private/var/folders/_y/v50r58vd4897phjb3nrc_7qm0000gp/T/MicrosoftAzureStorageExplorer 2/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:317:37)\n    at Request.self.callback (/private/var/folders/_y/v50r58vd4897phjb3nrc_7qm0000gp/T/MicrosoftAzureStorageExplorer 2/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/private/var/folders/_y/v50r58vd4897phjb3nrc_7qm0000gp/T/MicrosoftAzureStorageExplorer 2/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/private/var/folders/_y/v50r58vd4897phjb3nrc_7qm0000gp/T/MicrosoftAzureStorageExplorer 2/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/request/request.js:1079:12)",
  "code": "InvalidBlobOrBlock",
  "statusCode": 400,
  "requestId": "a6e20757-c01e-00c8-0f3f-b457fa000000"
}
```

**Comment by jinglouMSFT** [comment]
Storage Explorer should be able to handle uploading 7Mb blobs no problem. From the error message, it looks like the file you tried to upload may have some issues that caused the API to think it's not valid. Have tried to upload it using other tools such as AzCopy?  You can turn on AzCopy through the Experimental main menu.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of activity. Please comment/reopen if you have more info to share.
