### ISSUE TITLE
Unable to open blobs with name longer than 64 characters.

### ISSUE THREAD

**Issue by krialnmelin** [microsoft/AzureStorageExplorer#1096]
**Storage Explorer Version**: 1.6.2 and 1.5.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: 

**Bug description**
Unable to open blobs with name longer than 64 characters.

It seems to be a decrypting issue, as web download of the blob either from the portal or direct url works fine.

I can see the logic of it not working if the names are too long, so am seeking clarification is this is intended or not.

**Steps to Reproduce**
1. Create blob with any name longer than 64 characters
2.Try to Open/Download inside storage explorer

**Expected Experience**
Blob file should open in preferred text editor

**Actual Experience**

Operation fails with dialog box: "Invalid IV length"

**Additional Context**

Looked at this discussion to find the suggestion that it is something about the initialization vector (IV) of the AES algorithm

https://social.msdn.microsoft.com/Forums/vstudio/en-US/71a684b3-9e16-4e86-be88-9aa23af3988b/length-of-the-data-to-decrypt-is-invalid-with-aes

** Error log from web console **

Uncaught (in promise) Error: Invalid IV length
    at new Cipheriv (crypto.js:219:16)
    at Object.Cipheriv (crypto.js:217:12)
    at StringCrypto.encrypt (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-string-crypto\dist\StringCrypto.js:19:29)
    at Persistence.JobQueueManager._afterSerialization [as afterSerialization] (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-job-queue\dist\JobQueueManager.js:14:53)
    at new Persistence (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\nedb\lib\persistence.js:47:43)
    at new Datastore (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\nedb\lib\datastore.js:56:22)
    at new JobQueueManager (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-job-queue\dist\JobQueueManager.js:169:26)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\Components\JobQueue\ProviderBasedJobQueueManager.js:25:50
    at _fulfilled (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\q\q.js:883:30)

**Comment by MRayermannMSFT** [comment]
Hmmmm @krialnmelin , this is very odd. Haven't seen it before/this shouldn't happen. It also should have nothing to do with the length of your file name. Anyway, I have some steps for you to take if you don't mind. These should 1. help us understand what went wrong 2. hopefully unblock you.

1. Open Storage Explorer
2. Open Devtools (F12)
![image](https://user-images.githubusercontent.com/21112697/54721718-f0f26e80-4b1f-11e9-9035-c6759918e640.png)
3. Press ctrl+p
4. Type TextEncrypter.js and then hit enter
![image](https://user-images.githubusercontent.com/21112697/54721743-05cf0200-4b20-11e9-8f2a-0b5fc5a8ac81.png)
5. Set a breakpoint on line 53 by clicking on the number 53
![image](https://user-images.githubusercontent.com/21112697/54721751-12ebf100-4b20-11e9-9f64-679e2bc1c86b.png)
6. Try downloading/opening your file
7. When the breakpoint is hit, go to the console, type in ecryptionKey, press enter, and copy the resulting value to your clipboard
8. In the console again, type in `encryptionKey = undefined` and press enter
![image](https://user-images.githubusercontent.com/21112697/54721796-37e06400-4b20-11e9-822a-c1fc5d97fb4b.png)
9. Close the dev tools
10. Let us know if the download/open works now, and also let us know the value you copied to your clipboard.

**Comment by MRayermannMSFT** [comment]
@krialnmelin any luck?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
