### ISSUE TITLE
Copying VHDX to Azure storage

### ISSUE THREAD

**Issue by jwelsh17** [Microsoft/AzureStorageExplorer#1204]
**Storage Explorer Version**: _In which Storage Explorer version was the bug encountered?_
**Platform/OS**: _Linux Ubuntu? macOS High Sierra? Windows 10?_
**Architecture**: _i86? x64?_
**Regression From**: _Was this working in a previous version? If so, which one?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Be as clear and concise as you can._

**Expected Experience**
_A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected._

**Actual Experience**
_A clear and concise description of what actually happens. If applicable, add screenshots to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._
{
  "name": "StorageError",
  "message": "Operation could not be completed within the specified time.\nRequestId:497322da-e01c-0049-4959-d164f6000000\nTime:2019-03-03T00:44:13.5235428Z",
  "stack": "StorageError: Operation could not be completed within the specified time.\nRequestId:497322da-e01c-0049-4959-d164f6000000\nTime:2019-03-03T00:44:13.5235428Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "OperationTimedOut",
  "statusCode": 500,
  "requestId": "497322da-e01c-0049-4959-d164f6000000"
}

**Comment by jinglouMSFT** [comment]
Could you provide the following info?
- Which version Storage Explorer?
- Which version Windows? 10? 8? 7?
- Did you have AzCopy enabled? 
- How big is your VHDX?  Were you able to upload anything else? 
- Did you do upload or drag&drop?
- Did you see any other error before the timeout?

Thanks.

**Comment by craxal** [comment]
Possibly related to #1137.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of activity.
