### ISSUE TITLE
Error with PyInstaller during deployment

### ISSUE THREAD

**Issue by dchouren** [Microsoft/AzureStorageExplorer#1213]
**Platform/OS**: Linux Ubuntu
**Regression From**: Was working ~2 weeks ago

**Bug description**
I am developing an Azure function (Python) through VSCode. When I run 'func azure functionapp publish RootCauseAnalyzer --build-native-deps', I get a very long trace due to requirements.txt installing, culminating with this error:

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /root/.pyenv/versions/3.6.8/bin/python3.6 /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpz2hhiyyp:
  Traceback (most recent call last):
    File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-zxjtt7kz/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-zxjtt7kz/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-zxjtt7kz/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ModuleNotFoundError: No module named 'PyInstaller'
  
  ----------------------------------------
Command "/root/.pyenv/versions/3.6.8/bin/python3.6 /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpz2hhiyyp" failed with error code 1 in /tmp/pip-install-0d34rkni/pyinstaller
You are using pip version 19.0, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

My Dockerfile, if it's relevant:
```
FROM python:alpine

# If you prefer miniconda:
#FROM continuumio/miniconda3

LABEL Name=rca_vscode Version=0.0.1
EXPOSE 3000

WORKDIR /app
ADD . /app

# Using pip:
RUN python3 -m pip install -r requirements.txt
RUN pip install -U nltk
CMD ["python3", "-m", "rca_vscode"]

```

When I add the --no-bundler option I get:
```
func azure functionapp publish RootCauseAnalyzer --build-native-deps --no-bundler
Getting site publishing info...
Deleting the old .python_packages directory
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0'...done
Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0'..done
Running 'docker exec -t 1351fd mkdir -p /home/site/wwwroot/'..done
Running 'docker cp /var/folders/xl/gfzrh7wx7wbdvpltpzq80dm40000gn/T/tmpn7al24tmp/. 1351fd:/home/site/wwwroot'..done
Running 'docker cp /var/folders/xl/gfzrh7wx7wbdvpltpzq80dm40000gn/T/tmpK2hsLb.tmp 1351fd:python_docker_build.sh'..done
Running 'docker cp /var/folders/xl/gfzrh7wx7wbdvpltpzq80dm40000gn/T/tmpM3HURN.tmp 1351fd:python_bundle_script.py'..done
Running 'docker exec -t 1351fd chmod +x /python_docker_build.sh'..done
Running 'docker exec -t 1351fd chmod +x /python_bundle_script.py'..done
Running 'docker exec -t 1351fd /python_docker_build.sh'...........................................................done
Running 'docker cp 1351fd:/app.zip /var/folders/xl/gfzrh7wx7wbdvpltpzq80dm40000gn/T/og2oibbp.4s3'..done
Running 'docker kill 1351fd'..done
Preparing archive...
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

Do you know what is happening with Pyinstaller? This same deployment flow was working about two weeks ago.

**Comment by dchouren** [comment]
Missubmit in wrong repo!
