### ISSUE TITLE
wants to delete a storage created

### ISSUE THREAD

**Issue by bo2xl** [Microsoft/AzureStorageExplorer#1238]
{
  "name": "StorageError",
  "message": "Forbidden",
  "stack": "StorageError: Forbidden\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "Forbidden",
  "statusCode": 403,
  "requestId": "6b521900-501e-004d-01ff-da727f000000"
}

**Comment by MRayermannMSFT** [comment]
Hey @bo2xl , this type of error means you don't have the permissions needed to perform the action, in this case a delete. Can you check with the owner of the resource you are trying to delete to confirm that you don't have the needed permissions? Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of activity. Comment if you still need help. Thanks!
