### ISSUE TITLE
Multiple file uploads failing about 2/3 of the time with the update to 1.7.0

### ISSUE THREAD

**Issue by metalmensch** [microsoft/AzureStorageExplorer#1274]
**Storage Explorer Version**: 1.7.0
**Platform/OS**:  Windows 10?
**Architecture**: x64?
**Regression From**: Still works in 1.5

**Bug description**
Attempt to upload five files. First time failures happen about 2/3 of the tries. Retries fail about 1/3 of the time.

**Steps to Reproduce**
1. Drag and drop five files into a storage account container. (Files larger than 200mb). Where the files already exist.
2. Upload fails.

**Expected Experience**
Uploads always happen. Which was the case before the AzCopy change.

**Actual Experience**
Failures happen 2/3 of the time.

**Additional Context**
None needed.

**Comment by MRayermannMSFT** [comment]
@metalmensch , what error are you getting when the uploads fail?

**Comment by stewartadam** [comment]
I just had a large upload fail:
```
{
  "name": "StorageError",
  "message": "Operation could not be completed within the specified time.\nRequestId:f5dcf3c6-b01e-00bd-20df-ef27ef000000\nTime:2019-04-10T20:57:17.5734217Z",
  "stack": "StorageError: Operation could not be completed within the specified time.\nRequestId:f5dcf3c6-b01e-00bd-20df-ef27ef000000\nTime:2019-04-10T20:57:17.5734217Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "OperationTimedOut",
  "statusCode": 500,
  "requestId": "f5dcf3c6-b01e-00bd-20df-ef27ef000000"
}```

I have enabled the azcopy preview but it prompted me to do so as this file transfer was preparing, so I'm not sure if it actually ended up using it or not. Upon refreshing the file list the VHD appeared to be uploaded and the size was correct, but seeing as there wasn't a way to validate its integrity I initiated a re-upload.

**Comment by MRayermannMSFT** [comment]
Did your 2nd upload work...?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
