### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by saadsyed1** [microsoft/AzureStorageExplorer#1475]
**Storage Explorer Version**: 1.8.1
**Platform**: Windows
**Architecture**: ia32
**Build Number**: 20190510.6
**Commit**: 947fc741

The issue is only with accessing ADLS GEN 2 storage account. We can access blob storage and ADLS GEN 1. I know that this is not a permission issue as I have the owner permissions

**Comment by saadsyed1** [comment]
Version 1.8.1
Platform: Windows
Architecture: ia32
Build Number: 20190510.6
Commit: 947fc741
Support Id: 8f3c270d-9197-1e14-53ce-85d78eee4b93

**Comment by craxal** [comment]
@saadsyed1 Can you tell me _exactly_ which roles you are assigned? The Owner role does not contain any data layer permissions. If you have no other data layer permissions, this would explain why you can't list anything under the account. You may need the Storage Blob Data Owner role as well (see our [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=1804#role-based-access-control-permission-issues) for more info.

**Comment by saadsyed1** [comment]
I have added myself to the "STORAGE BLOB DATA CONTRIBUTOR" role and still encountering the same issue

**Comment by saadsyed1** [comment]
We tried this 
https://github.com/microsoft/AzureStorageExplorer/issues/1475?email_source=notifications&email_token=AIEN4HIVFN4ZVQ2ERACROF3P3JWPTA5CNFSM4HZB7RM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYCUQWQ#issuecomment-503662682

It worked for little bit but then again the same issue

**Comment by craxal** [comment]
Let's try this:
1. Launch Storage Explorer, sign in, and expand nodes until you see your storage accounts.
2. Attempt to expand your ADLS Gen 2 account until you see your blob containers or you get the error message.
3. Hit F12, select the Source tab, hit Ctrl+P, and enter FileSystemServiceClient.js.
4. Drop a breakpoint around line 18:
   ```ts
   return this.runOperation("listFileSystemsSegment", function (storageUrl) {
       return storageUrl.listFileSystemsSegment(AzureStorage.Aborter.none, continuation, options);
   });
   ```
5. Refresh the account node and expand the "Blob Containers" node. The breakpoint should be hit and pause execution.
6. Step into the `runOperation` function. Drop a breakpoint around line 131:
   ```ts
   if (this_1._isFallbackError(error_1)) {
       se_storage_explorer_sdk_1.TelemetryManager.sendEvent("StorageExplorer.Blobs.Fallback", { operation: opName, count: "" + (i + 1) });
       console.warn("Fallback for operation '" + opName + ", count " + (i + 1));
       this_1._raiseEvent("fallback");
   }
   ```

   Alternatively, drop a breakpoint around line 167:

   ```ts
   throw lastError;
   ```
7. Continue execution, and the second breakpoint should be hit.

Can you share the error details of `error_1` or `lastError`?

**Comment by zorgath** [comment]
Hey. So I am having a similar issue. Connection string works fine for all computers except one. That computer use to work, now it doesn't. Here is the stack for the lastError.
We are attempting to connect to our blob containers. When we expand the list, we receive the above/below error. 
"StorageError: This request is not authorized to perform this operation.
RequestId:130fafb8-f01e-0094-0ee5-354f64000000
Time:2019-07-08T23:36:32.9921891Z
    at Function.StorageServiceClient._normalizeError (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1205:23)
    at Object.StorageServiceClient._processResponse (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\services\storageserviceclient.js:751:50)
    at Request.processResponseCallback [as _callback] (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\azure-storage\lib\common\services\storageserviceclient.js:319:37)
    at Request.self.callback (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\request\request.js:185:22)
    at ZoneDelegate.invokeTask (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:151:47)
    at Request.ZoneTask.invoke (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:345:33)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\request\request.js:1157:10)
    at ZoneDelegate.invokeTask (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:151:47)
    at Request.ZoneTask.invoke (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:345:33)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)"

**Comment by craxal** [comment]
@zorgath OK, so you have a permissions error. What version of Storage Explorer are you using? Have you checked our [troubleshooting guide for RBAC permissions](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#role-based-access-control-permission-issues)?

**Comment by zorgath** [comment]
@craxal The problem is the connection string works fine on other computers. It is just this one instance of Storage Explorer where the connection string doesn't work.  So I don't believe it is an actual permissions error. Also, it previously worked a few months ago on that computer. The only difference between this computer and other computers/servers is that the one that is not working is VM hosted in Azure. 

The Storage Explorer where the connection string doesn't work was version 1.7.x. & 1.9.0.(We just uninstalled and reinstalled new version to see if that would fix the issue.) 
Permissions the strings provides: Read, Write, Delete, List, Add, Create, Update, Process

I did review the RBAC guide but nothing is popping out at me as something that is affecting us.

**Comment by craxal** [comment]
Do you know which operation exactly is throwing this error? Is it when you're trying to list blob containers? What other operations can you perform that you should have permissions for (access level, access policies, etc.)?

Seems strange that this same connection string would work on some machines but not on others. Possibly some invalid IP address range? You could also try opening a ticket from the Azure portal and share the request ID to get more information about why the operation failed.

**Comment by zorgath** [comment]
It happens when we are trying to list blob containers. (Well, any list operation in the storage account). I was able to change the soft delete policy, not seeing much of anything else I can do.

Strange is why I am posting here! :) I will check the IP Address range.

**Comment by zorgath** [comment]
We opened a ticket on the portal. We did track it down to an issue with the
IP Filter or networking. We tried powershell and AD authentication and both
failed as well. Thank you for your help.
