### ISSUE TITLE
storage error - The specified blob or block content is invalid

### ISSUE THREAD

**Issue by GHoh** [microsoft/AzureStorageExplorer#1561]
**Storage Explorer Version**: 1.7.0
**Build Number**: 20190305.10
**Platform/OS**: Windows
**Architecture**:
**Regression From**: ??

## Bug Description ##
An error is reported during attempt to upload a back up file to Blob Storage using Azure Portal and also Storage Explorer.  No progress is ever shown using the Azure portal UI, but the Storage Explorer does report an error.

## Steps to Reproduce ##
Visit storage account (Classic). 
Choose to Upload a file.
Select file and start upload.

## Expected Experience ##
We have been uploading files to this storage location from many months without issue.  This started around July 10th.

## Actual Experience ##
After a short period of time, the Storage Explorer shows an error in the Activities panel.

```json
{
  "name": "StorageError",
  "message": "The specified blob or block content is invalid.\nRequestId:23d2588d-501e-00a6-0840-3b9933000000\nTime:2019-07-15T19:07:25.6838753Z",
  "stack": "StorageError: The specified blob or block content is invalid.\nRequestId:23d2588d-501e-00a6-0840-3b9933000000\nTime:2019-07-15T19:07:25.6838753Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "InvalidBlobOrBlock",
  "statusCode": 400,
  "requestId": "23d2588d-501e-00a6-0840-3b9933000000"
}
```

**Comment by MRayermannMSFT** [comment]
Possibly related? #1345

**Comment by MRayermannMSFT** [comment]
@ghoh, are you still having issues with the latest storage explorer?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you still have problems.
