### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by dharishbabu007** [microsoft/AzureStorageExplorer#1562]
I am tying to connect from Azure Storage Explorer to Azure account. I am getting below error.

```
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 622f8cde-07b5-4d16-ab2a-6dc0c3a66e35, Error: {
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__error": {
    "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
    "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)"
  },
  "stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "management.azure.com",
  "host": "management.azure.com",
  "port": 443
}
Tenant Id: 73e72f79-bca8-4950-9657-bbf880560def, Error: {
  "name": "Error",
  "message": "getaddrinfo EAI_AGAIN management.azure.com:443",
  "__zone_symbol__error": {
    "originalStack": "Error: getaddrinfo EAI_AGAIN\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Object._errnoException (util.js:1024:11)\n    at errnoException (dns.js:55:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
    "zoneAwareStack": "Error: getaddrinfo EAI_AGAIN\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Object._errnoException (util.js:1024:11)\n    at errnoException (dns.js:55:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)"
  },
  "stack": "Error: getaddrinfo EAI_AGAIN\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Object._errnoException (util.js:1024:11)\n    at errnoException (dns.js:55:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "originalStack": "Error: getaddrinfo EAI_AGAIN\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Object._errnoException (util.js:1024:11)\n    at errnoException (dns.js:55:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "zoneAwareStack": "Error: getaddrinfo EAI_AGAIN\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Object._errnoException (util.js:1024:11)\n    at errnoException (dns.js:55:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__stack": "Error: getaddrinfo EAI_AGAIN\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Object._errnoException (util.js:1024:11)\n    at errnoException (dns.js:55:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "getaddrinfo EAI_AGAIN management.azure.com:443",
  "__zone_symbol__originalStack": "Error: getaddrinfo EAI_AGAIN\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Object._errnoException (util.js:1024:11)\n    at errnoException (dns.js:55:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__zoneAwareStack": "Error: getaddrinfo EAI_AGAIN\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Object._errnoException (util.js:1024:11)\n    at errnoException (dns.js:55:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "EAI_AGAIN",
  "errno": "EAI_AGAIN",
  "syscall": "getaddrinfo",
  "hostname": "management.azure.com",
  "host": "management.azure.com",
  "port": 443
}
```

**Comment by jinglouMSFT** [comment]
From the error message, it was a DNS lookup timed out error, meaning it is network connectivity error or proxy related error. Do you happen to use any proxy?  If so, did you have it configured in Storage Explorer?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
