### ISSUE TITLE
Closing storage explorer results in a Javascript error

### ISSUE THREAD

**Issue by juliusl** [Microsoft/AzureStorageExplorer#178]
[Window Title]
Microsoft Azure Storage Explorer

[Main Instruction]
Microsoft Azure Storage Explorer

[Content]
Version: 1.0.0

Platform: Windows
Architecture: ia32
Build Number: 20180415.2
Commit: 5d603052
Support Id: 447acca5-1fbc-4315-99c1-e9623e6880e5

Copyright © 2018 Microsoft. All rights reserved.

[OK]

#### Steps to Reproduce: ####

1. Closed storage explorer.

#### Expected Experience: ####
Closing storage explorer shouldn't result in an error.

#### Actual Experience: ####
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Object has been destroyed
    at WebContents.send (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\electron.asar\browser\api\web-contents.js:97:15)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\index.js:540:26
    at DownloadItem.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\ElectronUtilities.js:39:21)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at DownloadItem.emit (events.js:213:7)

[OK]

**Comment by MRayermannMSFT** [comment]
This is due to closing the window while an update is downloading. Going to won't fix as it doesn't cause any issues.
