### ISSUE TITLE
Not connecting with account

### ISSUE THREAD

**Issue by FilmonEmbaye** [microsoft/AzureStorageExplorer#2428]
```
Subscriptions for the following tenants could not be retrieved:
Tenant Id: 9652d7c2-1ccf-4940-8151-4a92bd474ed0, Error: {
  "name": "Error",
  "message": "tunneling socket could not be established, statusCode=407",
  "__zone_symbol__error": {
    "originalStack": "Error: tunneling socket could not be established, statusCode=407\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onConnect (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:166:19)\n    at Object.onceWrapper (events.js:273:13)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketOnData (_http_client.js:474:11)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Socket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)",
    "zoneAwareStack": "Error: tunneling socket could not be established, statusCode=407\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onConnect (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:166:19)\n    at Object.onceWrapper (events.js:273:13)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketOnData (_http_client.js:474:11)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Socket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)"
  },
  "stack": "Error: tunneling socket could not be established, statusCode=407\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onConnect (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:166:19)\n    at Object.onceWrapper (events.js:273:13)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketOnData (_http_client.js:474:11)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Socket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)",
  "originalStack": "Error: tunneling socket could not be established, statusCode=407\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onConnect (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:166:19)\n    at Object.onceWrapper (events.js:273:13)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketOnData (_http_client.js:474:11)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Socket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)",
  "zoneAwareStack": "Error: tunneling socket could not be established, statusCode=407\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onConnect (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:166:19)\n    at Object.onceWrapper (events.js:273:13)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketOnData (_http_client.js:474:11)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Socket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)",
  "__zone_symbol__stack": "Error: tunneling socket could not be established, statusCode=407\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onConnect (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:166:19)\n    at Object.onceWrapper (events.js:273:13)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketOnData (_http_client.js:474:11)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Socket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "tunneling socket could not be established, statusCode=407",
  "__zone_symbol__originalStack": "Error: tunneling socket could not be established, statusCode=407\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onConnect (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:166:19)\n    at Object.onceWrapper (events.js:273:13)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketOnData (_http_client.js:474:11)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Socket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)",
  "__zone_symbol__zoneAwareStack": "Error: tunneling socket could not be established, statusCode=407\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onConnect (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:166:19)\n    at Object.onceWrapper (events.js:273:13)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketOnData (_http_client.js:474:11)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Socket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)",
  "code": "ECONNRESET"
}
```

**Comment by MRayermannMSFT** [comment]
Are you behind a proxy? If so, have you enabled proxy settings? If yes, then what type of proxy are you behind? Also, is your proxy decrypting HTTPS traffic?

**Comment by FilmonEmbaye** [comment]
Yes, I got the Proxy set-up from my colleague, where it worked but not on my side.  I think in the config is only http stated. The URL of the proxy is http://proxy....net

**Comment by JasonYeMSFT** [comment]
Can you explain about what you mean by "it worked but not on your side"? Do you mean the same config works for Storage Explorer on some machine but not yours? Or do you mean that regular browsing works but Storage Explorer doesn't?

If it is the second case, please check the type of proxy you are using. We only support the basic proxy authentication. Advanced proxy protocols such as NTLM proxy are not supported.

If you are sure that your proxy type is supported, it would be helpful if you can capture a network trace so that we can further investigate what the problem is. [How to capture a trace using Fiddler](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#tools-for-diagnosing-issues)

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
