### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by agonyeye** [microsoft/AzureStorageExplorer#2516]
```json
{
  "name": "StorageError",
  "message": "The specified blob or block content is invalid.\nRequestId:cd698851-b01e-004d-08da-c58039000000\nTime:2020-01-08T04:16:59.3434768Z",
  "stack": "StorageError: The specified blob or block content is invalid.\nRequestId:cd698851-b01e-004d-08da-c58039000000\nTime:2020-01-08T04:16:59.3434768Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "InvalidBlobOrBlock",
  "statusCode": 400,
  "requestId": "cd698851-b01e-004d-08da-c58039000000"
}
```

**Comment by JasonYeMSFT** [comment]
Could you please provide the context of this error (e.g. Storage Explorer version, OS version, reproduce steps)? According to some existing reports, this error might be caused by a early cancel. In that case, you should be able to upload it again after a short amount of time.
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/87366e2b-74d9-4a8e-8996-c72bd08411ce/quotthe-specified-blob-or-block-content-is-invalidquot-when-using-setazurestorageblobcontent?forum=windowsazuredata

Let us know if this is consistently reproducing on your end.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
