### ISSUE TITLE
Storage Explorer Does Not Connect

### ISSUE THREAD

**Issue by JG-Spring** [microsoft/AzureStorageExplorer#2792]
I am trying to connect from my company to my Storage Account using Storage Explorer, and I got this error: "Subscriptions could not be loaded". Working from home, I do not have this issue. Could you provide what ports need to open in the firewall?
Report Issue:
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 300bfeb1-370b-4b19-8d5d-2c876345c4ec, Error: {
  "name": "Error",
  "message": "connect ECONNREFUSED 40.69.112.0:443",
  "__zone_symbol__error": {
    "originalStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
    "zoneAwareStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)"
  },
  "stack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "originalStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "zoneAwareStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "__zone_symbol__stack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "connect ECONNREFUSED 40.69.112.0:443",
  "__zone_symbol__originalStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "__zone_symbol__zoneAwareStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED",
  "syscall": "connect",
  "address": "40.69.112.0",
  "port": 443
}
Tenant Id: b5477562-3f93-4544-8cb3-a772ec1d321a, Error: {
  "name": "Error",
  "message": "connect ECONNREFUSED 40.69.112.0:443",
  "__zone_symbol__error": {
    "originalStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
    "zoneAwareStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)"
  },
  "stack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "originalStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "zoneAwareStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "__zone_symbol__stack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "connect ECONNREFUSED 40.69.112.0:443",
  "__zone_symbol__originalStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "__zone_symbol__zoneAwareStack": "Error: connect ECONNREFUSED 40.69.112.0:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED",
  "syscall": "connect",
  "address": "40.69.112.0",
  "port": 443
}

**Comment by jinglouMSFT** [comment]
Are you behind a proxy at your company? If so, you need to config the proxy settings first.

**Comment by JG-Spring** [comment]
Thanks for your quick answer. Could you provide info/link, what in the proxy needs to be configured, please?

From portal.azure.com, I can see the structure of Blob and File Share using Storage Explorer(Preview), but I cannot see the content.

Thanks a lot for your assistance.

**Comment by JasonYeMSFT** [comment]
First, if you have a proxy, you need to configure it in the proxy settings. [Proxy issues troubleshooting](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#proxy-issues)

For you 2nd issue about not being able to see the content, it seems like a permission issue where you have list permissions but no read permission. Is it the case that you can see what blobs (the list of blobs) are in the container but cannot download/open any blob of them?

**Comment by JG-Spring** [comment]
Again, thanks for your assistance.

Working on the Proxy now.

For the 2nd issue, I can do any operation from out side of my company. In my company, instead of see the content, I can see a big Storage Explorer icon(no error is displayed). I can access files(.TXT) using HTTPS from my company's network using SAS token.
