### ISSUE TITLE
Time-to-live of -1 doesn't work with emulator and Azure Stack

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3124]
1. Launch Storage Explorer while targeting Azure Stack.
2. Open a queue and click Add Message.
3. Enter a message and make sure "Time to live" is set to "None".
4. Click OK.

An error message comes up:
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>OutOfRangeQueryParameterValue</Code><Message>One of the query parameters specified in the request URI is outside the permissible range.
RequestId:73f1a32d-d255-0465-7043-d97658977c83
Time:2020-06-18T21:12:40.2629718Z</Message><QueryParameterName>messagettl</QueryParameterName><QueryParameterValue>-1</QueryParameterValue><MinimumAllowed>1</MinimumAllowed><MaximumAllowed>604800</MaximumAllowed><ExceptionDetails><ExceptionMessage>The value -1 specified for query parameter messagettl is out of range. Allowed range is from 1 to 604800.</ExceptionMessage><StackTrace>Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.OutOfRangeQueryParameterProtocolException: The value -1 specified for query parameter messagettl is out of range. Allowed range is from 1 to 604800. ---&gt; Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.OutOfRangeQueryParameterProtocolException: The value -1 specified for query parameter messagettl is out of range. Allowed range is from 1 to 604800.
   at Microsoft.Cis.Services.Nephos.Queue.Service.Protocols.Rest.QueueProtocolHead.&lt;PutMessageImpl&gt;d__50.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.&lt;ProcessImpl&gt;d__139.MoveNext()</StackTrace></ExceptionDetails></Error>
```

The reason for this error is because the API version used for Azure Stack does not yet support -1 for time to live.

**Comment by craxal** [comment]
We can disable the "None" option for Azure Stack. While we can do the same for emulator, Azurite in particular does support infinite time to live. Since there's no way for us to know which emulator we're working it, it's not worth trying to disable this option for emulators.

**Comment by MRayermannMSFT** [comment]
We're going to change to something other than what Craig said. We're going to:

- make the default time to live 7 days, just like it was in version 1.13.0 and older
- if requeue fails, an error message is going to be shown
