### ISSUE TITLE
Login with non home tenant AAD + intercepting proxy - Unable to retrieve child resources.  /  --ignore-certificate-errors throws Cannot read property 'MessageIgnoreSSLError'

### ISSUE THREAD

**Issue by felickz** [microsoft/AzureStorageExplorer#3164]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**: Windows 10 
**Architecture**: x64
**Regression From**:  not working previously

## Bug Description ##
When enabling MSAL Authentication preview, and further attempting to browse to a blob container - application fails with error: 

```
Unable to retrieve child resources.
Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:f52ea25c-801e-000d-431c-4f5351000000\nTime:2020-06-30T20:27:01.7967881Z</Message></Error>"]
```

FURTHER, if trying to use: 
`.\StorageExplorer.exe --ignore-certificate-errors`

Get some MessageIgnoreSSLError + still get failures 
```
193252 (Provider) >>> Loading 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\main\Resources\ResourceProvider'
193252 (Provider) >>> Loading 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\main\Configuration\ConfigurationProvider'
Resolved resource module './resources/Shell': 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\resources\Shell.json'
Resolved resource module './resources/Azure': 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\resources\Azure.json'
Resolved resource module './resources/Host': 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\resources\Host.json'
Resolved resource module './resources/Activities': 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\resources\Activities.json'
193252 (Provider) >>> Loading 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\main\UserAccountManagement\ServiceHubProvider'
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
193252 (ElectronRendererProviderProxy) >>> Provider proxy to Electron renderer created
Constructing dialog manager.
app-launch-complete
app-prestartup
193252 (Provider) >>> Loading 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\main\Telemetry\TelemetryProvider'
Unhandled Promise rejection: Cannot read property 'MessageIgnoreSSLError' of undefined ; Zone: <root> ; Task: null ; Value: TypeError: Cannot read property 'MessageIgnoreSSLError' of undefined
    at SslCertificateManager.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:27:93)
    at step (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:122:57)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:115:75
    at new ZoneAwarePromise (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:551:29)
    at Object.__awaiter (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:111:16)
    at SslCertificateManager._showSslWarning (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:22:24)
    at SslCertificateManager._checkForIgnoreCertsFlag (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:48:18)
    at SslCertificateManager._loadSslSettings (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:42:14)
    at new SslCertificateManager (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:19:14)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:123:19)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:404:3)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32) TypeError: Cannot read property 'MessageIgnoreSSLError' of undefined
    at SslCertificateManager.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:27:93)
    at step (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:122:57)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:115:75
    at new ZoneAwarePromise (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:551:29)
    at Object.__awaiter (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:111:16)
    at SslCertificateManager._showSslWarning (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:22:24)
    at SslCertificateManager._checkForIgnoreCertsFlag (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:48:18)
    at SslCertificateManager._loadSslSettings (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:42:14)
    at new SslCertificateManager (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:19:14)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:123:19)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:404:3)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
{
  rejection: TypeError: Cannot read property 'MessageIgnoreSSLError' of undefined
      at SslCertificateManager.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:27:93)
      at step (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:141:27)
      at Object.next (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:122:57)
      at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:115:75
      at new ZoneAwarePromise (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:551:29)
      at Object.__awaiter (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\tslib\tslib.js:111:16)
      at SslCertificateManager._showSslWarning (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:22:24)
      at SslCertificateManager._checkForIgnoreCertsFlag (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:48:18)
      at SslCertificateManager._loadSslSettings (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:42:14)
      at new SslCertificateManager (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:19:14)
      at Object.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:123:19)
      at Object.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\SslCertificateManager.js:404:3)
      at Module._compile (internal/modules/cjs/loader.js:968:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
      at Module.load (internal/modules/cjs/loader.js:816:32),
  promise: { __zone_symbol__state: 0, __zone_symbol__value: [Circular] },
  zone: {
    _properties: {},
    _parent: null,
    _name: '<root>',
    _zoneDelegate: {
      _taskCounts: [Object],
      zone: {},
      _parentDelegate: null,
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: null,
      _invokeDlgt: null,
      _invokeCurrZone: null,
      _handleErrorZS: null,
      _handleErrorDlgt: null,
      _handleErrorCurrZone: null,
      _scheduleTaskZS: null,
      _scheduleTaskDlgt: null,
      _scheduleTaskCurrZone: null,
      _invokeTaskZS: null,
      _invokeTaskDlgt: null,
      _invokeTaskCurrZone: null,
      _cancelTaskZS: null,
      _cancelTaskDlgt: null,
      _cancelTaskCurrZone: null,
      _hasTaskZS: null,
      _hasTaskDlgt: null,
      _hasTaskCurrZone: null
    }
  },
  task: null
}
```

## Steps to Reproduce ##
1. Enable MSAL Preview
2. Use machine that is  Intercepting proxy (bluecoat/netskope/etc) - to repro use fiddler.exe proxy
3. Open any storage account, nav to a blob container and choose Load More
4. Error Details popup occurs

## Expected Experience ##
Connect to blob

## Actual Experience ##
Error Occurs

## Additional Context ##
using intercepting proxy on corporate machine.  Additionally, tried importing intercepting cert in .cer/.crt/.pem format of base64 ascii encoded cert into Edit->SSL Certificates->Import Certificate - has no impact.  

As mentioned, attempted suggestion here (assuming it is cert/proxy related)  - https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-self-signed-certificate-in-certificate-chain-and-similar-errors  

`--ignore-certificate-errors`

**Comment by JasonYeMSFT** [comment]
@felickz, we only support base64 encoded certificate. Could you try getting a base64 encoded cert and import it instead? You also need to configure the proxy hostname and port in our proxy settings. If you haven't, in the app menu, please go to Edit -> Configure Proxy to setup your proxy settings.

**Comment by MRayermannMSFT** [comment]
@felickz at what point in the tree are you getting this error? Is it:

- after expanding the subscription node
- after expanding the storage accounts node
- after expanding a specific storage account node
- after expanding the blob containers node

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
