### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by navin2108** [microsoft/AzureStorageExplorer#3316]
**Storage Explorer Version**: 1.14.2
**Build Number**:  20200715.2
**Platform/OS**: Windows 10
**Architecture**: x64?
**Regression From**:  I am not sure. Encountered this issue for the first time

## Bug Description ##
Getting an error "Cannot read property 'uids' of undefined"
## Steps to Reproduce ##
1. Open Storage explorer and try connecting to a storage account using Access key and account name 

## Expected Experience ##
It should have connected to the storage account and should have shown the containers in the storage account

## Actual Experience ##
Got an error message which is provided in the additional context. The storage explorer asked me to log a ticket here.
## Additional Context ##
This is the error that I get in the storage explorer and the explorer asked me to log a ticket here

```
  "name": "TypeError",
  "message": "Cannot read property 'uids' of undefined",
  "__zone_symbol__error": {
    "originalStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:84:91)\n    at Object.finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:108:80)\n    at Function.<anonymous> (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:29:63)\n    at step (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at JsonPortMarshaler.standardMarshaler.<computed> [as finalizeOperation] (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:23:32)\n    at JsonPortMarshaler.onMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
    "zoneAwareStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:84:91)\n    at Object.finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:108:80)\n    at Function.<anonymous> (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:29:63)\n    at step (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at JsonPortMarshaler.standardMarshaler.<computed> [as finalizeOperation] (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:23:32)\n    at JsonPortMarshaler.onMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)"
  },
  "stack": "TypeError: Cannot read property 'uids' of undefined\n    at StorageExplorerProvider.<anonymous> (file:///C:/Users/v-namene/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:293:51)\n    at step (file:///C:/Users/v-namene/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:48:23)\n    at Object.next (file:///C:/Users/v-namene/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:29:53)\n    at fulfilled (file:///C:/Users/v-namene/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:20:58)",
  "originalStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:84:91)\n    at Object.finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:108:80)\n    at Function.<anonymous> (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:29:63)\n    at step (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at JsonPortMarshaler.standardMarshaler.<computed> [as finalizeOperation] (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:23:32)\n    at JsonPortMarshaler.onMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "zoneAwareStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:84:91)\n    at Object.finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:108:80)\n    at Function.<anonymous> (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:29:63)\n    at step (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at JsonPortMarshaler.standardMarshaler.<computed> [as finalizeOperation] (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:23:32)\n    at JsonPortMarshaler.onMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "__zone_symbol__stack": "TypeError: Cannot read property 'uids' of undefined\n    at StorageExplorerProvider.<anonymous> (file:///C:/Users/v-namene/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:293:51)\n    at step (file:///C:/Users/v-namene/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:48:23)\n    at Object.next (file:///C:/Users/v-namene/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:29:53)\n    at fulfilled (file:///C:/Users/v-namene/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:20:58)",
  "__zone_symbol__name": "TypeError",
  "__zone_symbol__message": "Cannot read property 'uids' of undefined",
  "__zone_symbol__originalStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:84:91)\n    at Object.finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:108:80)\n    at Function.<anonymous> (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:29:63)\n    at step (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at JsonPortMarshaler.standardMarshaler.<computed> [as finalizeOperation] (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:23:32)\n    at JsonPortMarshaler.onMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "__zone_symbol__zoneAwareStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:84:91)\n    at Object.finalizeOperation (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:108:80)\n    at Function.<anonymous> (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:29:63)\n    at step (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at JsonPortMarshaler.standardMarshaler.<computed> [as finalizeOperation] (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:23:32)\n    at JsonPortMarshaler.onMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (C:\\Users\\v-namene\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)"
```

**Comment by MRayermannMSFT** [comment]
@navin2108 can you try restarting and seeing if your account shows up under local and attached stoage accounts?

**Comment by navin2108** [comment]
Hello Matthew,

I have restarted the app multiple times but to no avail. I had shut down the machine and restarted it today and storage explorer opened in a clean state. No accounts are visible or the storage account which was added using key also does not seem to be connected. But when I try to add the account, it also says that connection name with 'Az300navin' already exists(screenshot attached).

[cid:c908f6a4-2dfb-47ff-8a6c-6ce2138a3ec0]

[cid:b51d3776-1623-4bda-a1c1-ee48cf1479f8]
Regards,
Navin
________________________________

**Comment by JasonYeMSFT** [comment]
@navin2108 your screenshots aren't uploaded. They show up as cid's.

**Comment by navin2108** [comment]
Hi Jason,

PFA screenshots
________________________________

**Comment by navin2108** [comment]
![Storage explorer 2](https://user-images.githubusercontent.com/63617882/89590646-0166ce80-d866-11ea-9994-0ef42db10ea1.jpg)
![Error](https://user-images.githubusercontent.com/63617882/89590648-0297fb80-d866-11ea-8171-3177d9f5e833.jpg)
![Storage explorer](https://user-images.githubusercontent.com/63617882/89590649-0297fb80-d866-11ea-993d-4d41376af1fb.jpg)

Attaching files directly on github.com

**Comment by navin2108** [comment]
Can I get an update on this?


Regards,
Navin
________________________________

**Comment by JasonYeMSFT** [comment]
Sorry, I wasn't able to reproduce what you have seen. Could you please get us some more information to help us figure out what is going on?

1. The reason why we show "az300navin" is already used is because we store an identifier of your custom connection (e.g. display name of this account connection) in local storage. You can try clearing the corrupted connection and re-attaching it. [Trouble shooting steps](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined). Although the header of the section says a different error, it is a very similar one to what you have seen.

2. If clearing and re-adding the connection doesn't help. There might be some problem accessing your Windows Credential Manager. To verify that you can search for it and see if it is full (having a lot of items) or is not showing you a item with the key "StorageExplorer_CustomConnections_Accounts_v1/az300navin". For the 1st case, you can clean the credential manager to give space for the new connections. If it is the 2nd case, let us know so that we can investigate when there might be problem accessing the credential manager.

**Comment by navin2108** [comment]
Hi Jason,

I did see 3-4 connections in the credential manager. I did clear/remove all connections but I am still getting the same error message.

Regards,
Navin
________________________________

**Comment by MRayermannMSFT** [comment]
@navin2108 it seems like you turned off the Storage Accounts features. If you go to settings you can re-enable it and your connections will show up.

Go to: Settings -> Services -> Storage Accounts, and make sure that first check box is checked. Then restart the app.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
