### ISSUE TITLE
ASE Get Subscriptions Failure Details

### ISSUE THREAD

**Issue by Aminator777** [microsoft/AzureStorageExplorer#3478]
**Dear all,

It's been two days now that I'm struggling with the connection to my Azure Subscriptions : Before, everything was working well and I was able to connect and see my subscriptions. However, now that is not possible anymore.

I did not change the network I'm connecting to, I am not behind a proxy or at least not aware of as, I can connect to the Azure portal.**

![2020-08-25 14_21_43-Alarms   Clock](https://user-images.githubusercontent.com/70208191/91173629-692e6d80-e6de-11ea-833e-59c436a507bc.png)

Subscriptions for the follwowing tenants could not be retrieved:
```
Tenant Id: b2ed466b-1ad5-4ea5-b19e-10f2abc41e7c, Error: {
  "name": "Error",
  "message": "read ECONNRESET",
  "__zone_symbol__error": {
    "originalStack": "Error: read ECONNRESET\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at errnoException (internal/errors.js:308:14)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:111:27)",
    "zoneAwareStack": "Error: read ECONNRESET\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at errnoException (internal/errors.js:308:14)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:111:27)"
  },
  "stack": "Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)",
  "originalStack": "Error: read ECONNRESET\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at errnoException (internal/errors.js:308:14)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:111:27)",
  "zoneAwareStack": "Error: read ECONNRESET\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at errnoException (internal/errors.js:308:14)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:111:27)",
  "__zone_symbol__stack": "Error: read ECONNRESET\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at errnoException (internal/errors.js:308:14)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:111:27)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "read ECONNRESET",
  "__zone_symbol__originalStack": "Error: read ECONNRESET\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at errnoException (internal/errors.js:308:14)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:111:27)",
  "__zone_symbol__zoneAwareStack": "Error: read ECONNRESET\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\Amine.HARASTANI\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at errnoException (internal/errors.js:308:14)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:111:27)",
  "errno": "ECONNRESET",
  "code": "ECONNRESET",
  "syscall": "read"
}


```

**Comment by MRayermannMSFT** [comment]
@Aminator777 can you check your windows environment variable settings for the either the variables `http_proxy` or `https_proxy`?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, please open a new issue.
