### ISSUE TITLE
Get Subscriptions Failure Details in Storage explorer

### ISSUE THREAD

**Issue by 829555** [microsoft/AzureStorageExplorer#3635]
```
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: b945c813-dce6-41f8-8457-5a12c2fe15bf, Error: {
  "name": "Error",
  "message": "tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n",
  "__zone_symbol__error": {
    "originalStack": "Error: tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:452:5)",
    "zoneAwareStack": "Error: tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:452:5)"
  },
  "stack": "Error: tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:452:5)",
  "originalStack": "Error: tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:452:5)",
  "zoneAwareStack": "Error: tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:452:5)",
  "__zone_symbol__stack": "Error: tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:452:5)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n",
  "__zone_symbol__originalStack": "Error: tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:452:5)",
  "__zone_symbol__zoneAwareStack": "Error: tunneling socket could not be established, cause=write EPROTO 250594096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\829555\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:452:5)",
  "code": "ECONNRESET"
}
```

**Comment by MRayermannMSFT** [comment]
@829555 are you working with an emulator or Azure?

If an emulator, are you trying to use HTTPS with the emulator?

If Azure, are you behind a proxy which is maybe like HTTP only or maybe you had to import an HTTPS cert for it?

We've only seen this error when something is wrong with an HTTPS cert/things of that nature.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still encountering this problem, please open a new issue. Thanks!
