### ISSUE TITLE
Storage Explorer does not list blobs locally or from the azure portal

### ISSUE THREAD

**Issue by prashantjoge** [microsoft/AzureStorageExplorer#3766]
**Storage Explorer Version**: 
1.16.0
**Build Number**: 
20201109.5
**Platform/OS**: 
5.9.6-arch1-1
**Architecture**: 
x64
**Regression From**:  
Did not notice this issue before. Do not remember the older version
## Bug Description ##

Blob containers are not being displayed under the blob storage account. Issue noticed both from portal and azurite
## Steps to Reproduce ##

created a storage account in the portal. The container is not getting listed in Azure Storage Explorer. 
The same is issue was noticed when connecting to a local azurite blob.
No issues listing other resources: files, queues & tables

## Expected Experience ##

Expected to see blob containers so that  blobs can be created
## Actual Experience ##

https://imgur.com/a/ifJznNB
## Additional Context ##

When you refresh the account the following error is generated
Unable to retrieve child resources.

Details:
```json
{
  "name": "TypeError",
  "message": "Object prototype may only be an Object or null: undefined",
  "__zone_symbol__error": {
    "originalStack": "Error: Object prototype may only be an Object or null: undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/usr/local/storageExplorer/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/usr/local/storageExplorer/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
    "zoneAwareStack": "Error: Object prototype may only be an Object or null: undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/usr/local/storageExplorer/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/usr/local/storageExplorer/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)"
  },
  "stack": "TypeError: Object prototype may only be an Object or null: undefined\n    at setPrototypeOf (<anonymous>)\n    at Object.__extends (/usr/local/storageExplorer/resources/app/node_modules/se-blob-extension/node_modules/tslib/tslib.js:68:9)\n    at /usr/local/storageExplorer/resources/app/node_modules/se-blob-extension/dist/src/Clients/BlobStorageClient.js:51:13\n    at Object.<anonymous> (/usr/local/storageExplorer/resources/app/node_modules/se-blob-extension/dist/src/Clients/BlobStorageClient.js:115:2)\n    at Module._compile (internal/modules/cjs/loader.js:968:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)\n    at Module.load (internal/modules/cjs/loader.js:816:32)\n    at Module._load (internal/modules/cjs/loader.js:728:14)\n    at Function.Module._load (electron/js2c/asar.js:748:26)\n    at Function.load [as _load] (/usr/local/storageExplorer/resources/app/out/app/SdkLoading/SdkRequireInterceptor.js:26:37)",
  "originalStack": "Error: Object prototype may only be an Object or null: undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/usr/local/storageExplorer/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/usr/local/storageExplorer/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
  "zoneAwareStack": "Error: Object prototype may only be an Object or null: undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/usr/local/storageExplorer/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/usr/local/storageExplorer/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
  "__zone_symbol__stack": "TypeError: Object prototype may only be an Object or null: undefined\n    at setPrototypeOf (<anonymous>)\n    at Object.__extends (/usr/local/storageExplorer/resources/app/node_modules/se-blob-extension/node_modules/tslib/tslib.js:68:9)\n    at /usr/local/storageExplorer/resources/app/node_modules/se-blob-extension/dist/src/Clients/BlobStorageClient.js:51:13\n    at Object.<anonymous> (/usr/local/storageExplorer/resources/app/node_modules/se-blob-extension/dist/src/Clients/BlobStorageClient.js:115:2)\n    at Module._compile (internal/modules/cjs/loader.js:968:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)\n    at Module.load (internal/modules/cjs/loader.js:816:32)\n    at Module._load (internal/modules/cjs/loader.js:728:14)\n    at Function.Module._load (electron/js2c/asar.js:748:26)\n    at Function.load [as _load] (/usr/local/storageExplorer/resources/app/out/app/SdkLoading/SdkRequireInterceptor.js:26:37)",
  "__zone_symbol__name": "TypeError",
  "__zone_symbol__message": "Object prototype may only be an Object or null: undefined",
  "__zone_symbol__originalStack": "Error: Object prototype may only be an Object or null: undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/usr/local/storageExplorer/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/usr/local/storageExplorer/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
  "__zone_symbol__zoneAwareStack": "Error: Object prototype may only be an Object or null: undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/usr/local/storageExplorer/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/usr/local/storageExplorer/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/usr/local/storageExplorer/resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:122:57)\n    at /usr/local/storageExplorer/resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/usr/local/storageExplorer/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)"
}
```

**Comment by JasonYeMSFT** [comment]
Someone has seen a similar error in #3639. Could you try doing a clean re-install?

For macOS, you should:
- delete the .app from the Applications folder
- re-download from https://storageexplorer.com
- unzip
- drag and drop into the Applications folder

For linux, if you used .tar.gz package, this should mean:
- delete all files you extracted from the package
- redownload package
- extract and install where you'd like

If you did snap, then:
- `snap remove storage-explorer`
- `snap install storage-explorer`
- `snap connect storage-explorer:password-manager-service :password-manager-service`

If possible, you can also try installing Storage Explorer on a different machine to help us see whether the root cause is a client side issue or a Azure service side issue.

Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues, please either reopen this issue or open a new issue.
