### ISSUE TITLE
unable to create new blob container or retrieve the existing

### ISSUE THREAD

**Issue by RoopaP1808** [microsoft/AzureStorageExplorer#3780]
Unable to retrieve child resources.

Details:
```json
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000",
  "__zone_symbol__error": {
    "originalStack": "Error: request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
    "zoneAwareStack": "Error: request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)"
  },
  "stack": "FetchError: request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at ClientRequest.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:210:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "originalStack": "Error: request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "zoneAwareStack": "Error: request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "__zone_symbol__stack": "FetchError: request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at ClientRequest.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:210:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "__zone_symbol__name": "FetchError",
  "__zone_symbol__message": "request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000",
  "__zone_symbol__originalStack": "Error: request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "__zone_symbol__zoneAwareStack": "Error: request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\roopapex\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}
```

**Comment by JasonYeMSFT** [comment]
Do you have the emulator running?

**Comment by RibbonFish** [comment]
Exactly same issue on navigating my Remote repository / Doesn't want to list Blob containers with that issue

**Comment by MRayermannMSFT** [comment]
@RibbonFish so you are getting a ECONNREFUSED when trying to work with a real storage account in Azure? In that case, are you behind a proxy and if so have you set that up in settings yet?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of responses. If you are still having problems, please open a new issue. Thanks!
