### ISSUE TITLE
Upload blob fails: no such host

### ISSUE THREAD

**Issue by bbsdddougla** [microsoft/AzureStorageExplorer#3812]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201109.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  1.15.1

## Bug Description ##
Similar to https://github.com/microsoft/AzureStorageExplorer/issues/2237 the client reports failing to resolve the host when uploading files.

## Steps to Reproduce ##
Attempt to upload any file to a blob container by dragging and dropping from Windows Explorer to Storage Explorer

## Expected Experience ##
Blob is uploaded to container.

## Actual Experience ##
Upload fails after long timeout.

## Additional Context ##
Upload works with powershell commands described here after signing into storage account using the retrieved storage context from Get-AzStorageAccount:
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-powershell#upload-blobs-to-the-container

Download also fails, with no log message, hanging on "Starting transfer".

Upload fails with any file, regardless of size.

Tried on office VPN, off office VPN.
Tried with netsh winhttp proxy on and off (targeting Telerik Fiddler)

Log in .azcopy directory contains repeats of:

```2020/11/24 06:04:08 ==> REQUEST/RESPONSE (Try=1/2.2048593s, OpTime=2.2048593s) -- REQUEST ERROR
   HEAD https://MYSTORAGEACCOUNT.blob.core.windows.net/MYCONTAINER/MYFILE?se=2020-12-24t06%3A04%3A06z&sig=-REDACTED-&sp=rwl&sr=c&sv=2019-12-12&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.16.0, win32,  AzCopy/10.7.0 Azure-Storage/0.10 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [d121caff-6ad7-40d1-7df2-8921ad029244]
   X-Ms-Version: [2019-12-12]
   
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Head https://MYSTORAGEACCOUNT.blob.core.windows.net/MYCONTAINER/MYFILE?se=2020-12-24T06%3A04%3A06Z&sig=-REDACTED-&sp=rwl&sr=c&sv=2019-12-12&timeout=901: proxyconnect tcp: dial tcp: lookup off: no such host

goroutine 124 [running]:
github.com/Azure/azure-storage-azcopy/ste.stack(0xc0013de300, 0xc001078500, 0x0)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:232 +0xa4
github.com/Azure/azure-storage-azcopy/ste.NewRequestLogPolicyFactory.func1.1(0xd962c0, 0xc0004d6420, 0xc0000a5200, 0x10, 0x0, 0x0, 0xc0013f22c0)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:146 +0x7ac
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0013ea140, 0xd962c0, 0xc0004d6420, 0xc0000a5200, 0xc0013f2348, 0xc0011becf8, 0xa, 0x2030004)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0xd962c0, 0xc0004d6420, 0xc0000a5200, 0xc0011bedd0, 0xc0011bed80, 0x40c7c0, 0xc0013ea1e0)
	/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:78 +0x1b8
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0007e8120, 0xd962c0, 0xc0004d6420, 0xc0000a5200, 0x10, 0x10, 0xb79560, 0x30)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0xd86280, 0xc0007e8120, 0xc0013fa000, 0xd962c0, 0xc0004d6420, 0xc0000a5200, 0x0, 0x12ae220, 0xc0011bede0, 0x4310d8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zz_generated_responder_policy.go:33 +0x5a
github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_credential_anonymous.go:54
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do(0xc00087a250, 0xd962c0, 0xc0004d6420, 0xc0000a5200, 0x0, 0x0, 0x0, 0xc0011bef00)
	/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x62
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00087a260, 0xd962c0, 0xc0004d6420, 0xc0000a5200, 0xc0004d6420, 0xc00087a370, 0xc000000001, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0xd96240, 0xc001096180, 0xc0000a4500, 0x10, 0xb27840, 0x64492d747301, 0xc0013f2160)
	/home/vsts/work/1/s/ste/xferRetrypolicy.go:384 +0x70f
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0013ea190, 0xd96240, 0xc001096180, 0xc0000a4500, 0xc0013f2218, 0x30, 0x28, 0x8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0xd96240, 0xc001096180, 0xc0000a4500, 0x10, 0xb27840, 0x40d001, 0xc0013f2160)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_policy_unique_request_id.go:19 +0xb5
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0007e8a80, 0xd96240, 0xc001096180, 0xc0000a4500, 0xc0013f2200, 0x67, 0xc0007f8000, 0xc0011bf2c8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0xd96240, 0xc001096180, 0xc0000a4500, 0x1, 0x0, 0x1, 0xc000806030)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_policy_telemetry.go:34 +0x164
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0013ee060, 0xd96240, 0xc001096180, 0xc0000a4500, 0xc0013ee060, 0xc0000a4500, 0xc0011bf398, 0x40d06f)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc0010960c0, 0xd96240, 0xc001096180, 0xd86380, 0xc0013fa000, 0xc0000a4500, 0x28, 0xc000804300, 0x32, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:129 +0x88
github.com/Azure/azure-storage-blob-go/azblob.blobClient.GetProperties(0xc0000c41c0, 0x5, 0x0, 0x0, 0x0, 0xc0000c41c8, 0x28, 0xc000804300, 0x32, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zz_generated_blob.go:943 +0x40c
github.com/Azure/azure-storage-blob-go/azblob.BlobURL.GetProperties(0xc0000c41c0, 0x5, 0x0, 0x0, 0x0, 0xc0000c41c8, 0x28, 0xc000804300, 0x32, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/url_blob.go:186 +0x13e
github.com/Azure/azure-storage-azcopy/ste.(*blockBlobSenderBase).RemoteFileExists(0xc00136e000, 0xc000000000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vsts/work/1/s/ste/sender-blockBlob.go:156 +0xd8
github.com/Azure/azure-storage-azcopy/ste.anyToRemote_file(0xdae4a0, 0xc0001da0e0, 0x800000, 0xc001058090, 0x22, 0x0, 0xc0000c41c0, 0xcf, 0x0, 0x0, ...)
	/home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:238 +0x10de
github.com/Azure/azure-storage-azcopy/ste.anyToRemote(0xdae4a0, 0xc0001da0e0, 0xd84700, 0xc0010960c0, 0x1a54068, 0xc000020028, 0xc79de0, 0xc79df0)
	/home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:183 +0x239
github.com/Azure/azure-storage-azcopy/ste.parameterizeSend.func1(0xdae4a0, 0xc0001da0e0, 0xd84700, 0xc0010960c0, 0x1a54068, 0xc000020028)
	/home/vsts/work/1/s/ste/xfer.go:77 +0x7a
github.com/Azure/azure-storage-azcopy/ste.(*jobPartMgr).StartJobXfer(0xc00010e900, 0xdae4a0, 0xc0001da0e0)
	/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:568 +0x78
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).StartJobXfer(0xc0001da0e0)
	/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:211 +0x4f
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).transferProcessor.func1(0xdae4a0, 0xc0001da0e0)
	/home/vsts/work/1/s/ste/JobsAdmin.go:465 +0x18f
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).transferProcessor(0xc00006c000, 0x2c)
	/home/vsts/work/1/s/ste/JobsAdmin.go:473 +0x95
created by github.com/Azure/azure-storage-azcopy/ste.initJobsAdmin
	/home/vsts/work/1/s/ste/JobsAdmin.go:219 +0x7bd
`
with intermittent examples of this when trying to upload empty files:
`
2020/11/24 06:05:18 PERF: primary performance constraint is Unknown. States: X:  5, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  5, GRs: 128
2020/11/24 06:05:18 100.0 %, 0 Done, 0 Failed, 5 Pending, 0 Skipped, 5 Total, 
```

**Comment by MRayermannMSFT** [comment]
@bbsdddougla what is the value of your proxy source setting in storage explorer? 
![image](https://user-images.githubusercontent.com/21112697/100651551-76b94c00-32fa-11eb-86c2-4aa8d9407a0c.png)

**Comment by bbsdddougla** [comment]
"Do not use proxy" is the setting.

**Comment by MRayermannMSFT** [comment]
@bbsdddougla ok, can you try going to the setting, Settings -> Transfers -> AzCopy -> Disable AzCopy Proxy Usage, checking that checkbox, and then trying again?

**Comment by bbsdddougla** [comment]
@MRayermannMSFT  Thanks, toggling that setting did work. Is there something to check besides the WinHTTP proxy? Fiddler is off, and netsh shows this:

```Powershell
PS C:\temp> netsh winhttp show proxy

Current WinHTTP proxy settings:

    Proxy Server(s) :  off
    Bypass List     :  (none)
```

**Comment by MRayermannMSFT** [comment]
@bbsdddougla that's a great question that I do not know the answer to. ☹️ You could try asking on the AzCopy v10 repo.

Long term, we'd like to make turning that setting on the default, but we don't know how many people are relying on it. Or in other words, how many people would we break if we changed it to be default. We're trying to convince AzCopy to output a message when it is using an auto-detected proxy so we can figure out that number. Maybe it could also output where it is getting the proxy from?
