### ISSUE TITLE
Error when opening storage explorer

### ISSUE THREAD

**Issue by erfannariman** [microsoft/AzureStorageExplorer#3860]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201109.5
**Platform/OS**: macOS Big Sur
**Architecture**: x64
**Regression From**: Not sure.

## Bug Description ##
This bug pops up after opening storage explorer. See details below

## Steps to Reproduce ##
1. Open storage explorer

## Additional Context ##
```
Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Hub Controller process exited prematurely with signal 'SIGABRT'.",
  "__zone_symbol__error": {
    "originalStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
    "zoneAwareStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)"
  },
  "stack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at ControllerConnection.onControllerProcessExited (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)\nFrom previous event:\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at defer (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:582:19)\n    at Promise.then (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:828:20)\n    at ControllerConnection.connectImpl (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:48:14)\n    at Function.ControllerConnection.connect (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:31:27)\n    at HubLookup.getLocationService (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubLookup.js:20:80)\n    at HubClient.requestServiceWithRetries (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubClient.js:74:21)\n    at HubClient.requestService (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubClient.js:62:21)\n    at ElectronAadAccountProviderClient.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:57:74)\n    at Generator.next (<anonymous>)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:10:71\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at __awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:6:12)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:56:27",
  "originalStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "zoneAwareStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "__zone_symbol__stack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at ControllerConnection.onControllerProcessExited (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)\nFrom previous event:\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at defer (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:582:19)\n    at Promise.then (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:828:20)\n    at ControllerConnection.connectImpl (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:48:14)\n    at Function.ControllerConnection.connect (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:31:27)\n    at HubLookup.getLocationService (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubLookup.js:20:80)\n    at HubClient.requestServiceWithRetries (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubClient.js:74:21)\n    at HubClient.requestService (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubClient.js:62:21)\n    at ElectronAadAccountProviderClient.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:57:74)\n    at Generator.next (<anonymous>)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:10:71\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at __awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:6:12)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:56:27",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "Hub Controller process exited prematurely with signal 'SIGABRT'.",
  "__zone_symbol__originalStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "__zone_symbol__zoneAwareStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "signal": "SIGABRT"
}
```

**Comment by MRayermannMSFT** [comment]
@erfannariman you're not on an M1 mac are you?

Either way, please do the following:

1. In Storage Explorer settings, turn on Verbose Authentication Logging under, Application -> Sign-in
2. Close Storage Explorer
3. Delete ~/.ServiceHub/logs
4. Start Storage Explorer
5. Do everything you do to reproduce this problem
6. After it reproduces, zip up ~/.ServiceHub/logs, and attach it here

Thanks.

**Comment by erfannariman** [comment]
> @erfannariman you're not on an M1 mac are you?

No I am still on an intel mac.

> 
> Either way, please do the following:
> 
> 1. In Storage Explorer settings, turn on Verbose Authentication Logging under, Application -> Sign-in
> 2. Close Storage Explorer
> 3. Delete ~/.ServiceHub/logs
> 4. Start Storage Explorer
> 5. Do everything you do to reproduce this problem
> 6. After it reproduces, zip up ~/.ServiceHub/logs, and attach it here
> 
> Thanks.

Weird part about this error is that it shows up once in a while. So it's hard to reproduce, but if I get the change I will zip the logs up and attach them here.

**Comment by MRayermannMSFT** [comment]
I'm going to go ahead and close this bug for now. Feel free to leave that setting checked. Then if you ever get the error again, you can just send us the logs. Thanks!
