### ISSUE TITLE
Cannot open Azure resources with Azure Storage Explorer 1.17.0

### ISSUE THREAD

**Issue by BDuechting** [microsoft/AzureStorageExplorer#3956]
Details:
{
  "name": "Error",
  "message": "Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token",
  "__zone_symbol__error": {
    "originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
    "zoneAwareStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)"
  },
  "stack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at Object.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-managed-disks-extension\\dist\\src\\AzureSdkHelpers\\CredentialFactory.js:29:31)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at fulfilled (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:112:62)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "zoneAwareStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "__zone_symbol__stack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at Object.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-managed-disks-extension\\dist\\src\\AzureSdkHelpers\\CredentialFactory.js:29:31)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at fulfilled (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:112:62)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token",
  "__zone_symbol__originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "__zone_symbol__zoneAwareStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\berndeu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)"
}

**Comment by BDuechting** [comment]
After restarting Azure Storage Explorer I am able to see my Azure resources. Close Issue

**Comment by BDuechting** [comment]
See above comment
