### ISSUE TITLE
Unable to retrieve child resources. Details: ["Error:Unable to retrieve authentication token."]

### ISSUE THREAD

**Issue by saumyabahuk** [microsoft/AzureStorageExplorer#4095]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

## Steps to Reproduce ##
while reentering credentials, this error is given.

**Comment by Olarm** [comment]
I seem to have gotten the same issue just now as well.
Error appeared after opening the program without performing any actions.

Storage Explorer Version: 1.17.0
Build Number: 20201211.10 
Platform/OS: macOS
Architecture: x64


```
Unable to retrieve child resources.

  Details:
  {
    "name": "Error",
    "message": "Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token",
    "__zone_symbol__error": {
          "originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
          "zoneAwareStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)"
        },
        "stack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at Object.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-managed-disks-extension/dist/src/AzureSdkHelpers/CredentialFactory.js:29:31)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at fulfilled (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:112:62)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
        "zoneAwareStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
        "__zone_symbol__stack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at Object.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-managed-disks-extension/dist/src/AzureSdkHelpers/CredentialFactory.js:29:31)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at fulfilled (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:112:62)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "__zone_symbol__name": "Error",
        "__zone_symbol__message": "Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token",
        "__zone_symbol__originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)",
        "__zone_symbol__zoneAwareStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:197:55)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/main/NodeProcessProviderProxy.js:141:62)\n    at step (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:122:57)\n    at /private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:115:75\n    at new ZoneAwarePromise (/private/var/folders/dx/1d9gsg192jlcykf1b9ght2840000gn/T/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)"
  }
```

**Comment by apowell-barfoot** [comment]
Had the same issue, But again as mentioned above. Clicking to re-enter credentials and completing the process will resolve the issue. 
The problem is the error could be handled a lot nicer, to make the user experience better. Shouldn't need to come here and report such a simple thing.

**Comment by saumyabahuk** [comment]
This error has been persistent. On re-entering credentials, still gives the same error.

**Comment by MRayermannMSFT** [comment]
It sounds like y'all are all aware of how to get rid of the error dialog. We'll be hiding it starting in our next release as well.
