### ISSUE TITLE
Azure Storage Explorer, add an account issue, lowei@microsoft.com Subscription could not be loaded. 

### ISSUE THREAD

**Issue by longwei77** [microsoft/AzureStorageExplorer#4256]
```
Subscriptions for the following tenants could not be retrieved:
Tenant Id: 72f988bf-86f1-41af-91ab-2d7cd011db47, Error: {
  "name": "Error",
  "message": "tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443",
  "__zone_symbol__error": {
    "originalStack": "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
    "zoneAwareStack": "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)"
  },
  "stack": "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
  "originalStack": "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
  "zoneAwareStack": "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
  "__zone_symbol__stack": "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443",
  "__zone_symbol__originalStack": "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
  "__zone_symbol__zoneAwareStack": "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at ClientRequest.onError (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel-agent\\index.js:177:17)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at ClientRequest.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at ZoneDelegate.invokeTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Users\\lowei\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
  "code": "ECONNRESET"
}
```

**Comment by MRayermannMSFT** [comment]
@longwei77 it looks like you've setup proxy settings for 127.0.0.1:443. That also appears to be an HTTPS proxy. Did you need to add an certs to Storage Explorer? Is your proxy running (we think this is most likely)? If you disable proxy settings do things work? Have you tried from another machine or network?

**Comment by longwei77** [comment]
Hi Matt,

Sorry, I did not give you my update on time. After disabling the proxy, ASE came back to work. Is it required to set the proxy to 127.0.0.1:443. What is 127.0.0.1:443 IP address?

Thank you for your helps,

Long

**Comment by JasonYeMSFT** [comment]
Storage Explorer don't require a proxy to work. 127.0.0.1:443 is the default HTTPS port of your local machine and we don't know what that is in your situation. If you are able to reproduce the issue, could you tell us what was your old proxy setting that leads to this problem (e.g. app setting with that IP address, use environment variable)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, feel free to open a new issue. Thanks.
