### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by gdignard** [Microsoft/AzureStorageExplorer#435]
**Storage Explorer Version**:  v1.2.0
**Platform/OS Version**: Windows 10 Pro v1709 build 16299.492

#### Steps to Reproduce: ####
1. Unknown

#### Expected Experience: ####
App quits

#### Actual Experience: ####
App throws an exception on quit (contents of dialog box below)

A JavaScript error occurred in the main process

Uncaught Exception
Error: Object has been destroyed
  at WebContents.send (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\electron.asar\browser\api\web-contents.js:100:15)
  at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-electron-file-downloader\dist\ElectronFileDo....:34
  at DownloadItem.<anonymous> (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-electron-file-downloader\dist\ElectronFileDo...:17)
  at Object.onceWrapper (events.js:317:30)
  at emitTwo (events.js:126:13)
  at DownloadItem.emit (events.js:214:7)

#### Bonus Suggestion ####

There may be errors in the stack trace above. You might want to consider either adding a "Copy Text" button to this dialog or make the text displayed is selectable/copyable if you want more people to bother sending you these details. Typing it out is not ideal.

**Comment by craxal** [comment]
Can you consistently reproduce this error? What do you usually do in the app before exiting? How do you close the app? Does this happen if you open then close right after?

Do you have a screenshot of the dialog in question? It's a good suggestion, but it may be a dialog we have no control over.

**Comment by gdignard** [comment]
Craig -

Thanks for following up.

No, it only happened once. I tried to reproduce it (in v1.2.0), but it
never happened again.

I've since updated from v1.2.0 to v1.3.1.

That one time it did happen, there weren't many steps in what I had just
finished doing.

I launched the app, navigated to a table, selected All of the records
(there weren't many and they fit on a single page. I don't recall if I
selected all via All on Page or All in Cache, or ctrl-a but doubt that's an
impactful detail), deleted the records and quit the app. (A timing issue
with the delete not completed before the quit or some form of race
condition as it quits?)

Hope that helps; sorry I don't have more detail

- Gilles
