### ISSUE TITLE
Failed to execute durable function on storage emulator

### ISSUE THREAD

**Issue by vaibhav-bwk** [microsoft/AzureStorageExplorer#4484]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10

### Architecture

i86

### Bug Description

I have created durable function which  is failing to trigger the orchestration function on my local machine using storage emulator. It was working properly. But now it is failing.
On executing Orchestration client, getting below error :

An error occurred while processing messages on devgranttaskhub-control-02: Microsoft.WindowsAzure.Storage.StorageException: Server encountered an internal error. Please try again after some time.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.Messaging.TaskHubQueue.AddMessageAsync(TaskMessage taskMessage, OrchestrationInstance sourceInstance, SessionBase session) in C:\source\durabletask\src\DurableTask.AzureStorage\Messaging\TaskHubQueue.cs:line 140
Request Information
 RequestID:e5302840-252e-45da-becd-3bd394f0f984

StatusMessage:Server encountered an internal error. Please try again after some time.
ErrorCode:InternalError
 ErrorMessage:Server encountered an internal error. Please try again after some time.

I am not getting what is wrong with storage emulator. I did uninstall and installed it again. Still issue persist. Any idea how to fix this issue?

### Steps to Reproduce

1. Debug durable function locally.
2. Check the log.

### Actual Experience

Facing an error while executing durable function.

An error occurred while processing messages on devgranttaskhub-control-02: Microsoft.WindowsAzure.Storage.StorageException: Server encountered an internal error. Please try again after some time.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.Messaging.TaskHubQueue.AddMessageAsync(TaskMessage taskMessage, OrchestrationInstance sourceInstance, SessionBase session) in C:\source\durabletask\src\DurableTask.AzureStorage\Messaging\TaskHubQueue.cs:line 140
Request Information
 RequestID:e5302840-252e-45da-becd-3bd394f0f984

**Comment by MRayermannMSFT** [comment]
Hi @vaibhav-bwk, the .NET Storage Emulator is no longer being actively developed. [Azurite](https://github.com/Azure/Azurite) is the Storage Emulator platform going forward. Azurite supersedes the Azure Storage Emulator. I would recommend you try using Azurite instead. Additionally, as this repo is for **Storage Explorer**, we are unable to help you with this issue.
