### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by ashfaq-rakuten** [microsoft/AzureStorageExplorer#4534]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Storage Explorer Build Number

20210425.1

### Platform

macOS

### OS Version

macmojave 10.14.6

### Bug Description

When we are accessing the Azure storage account from Azure Storage Explorer getting the below error. 

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://xxxx.blob.core.windows.net/?include=metadata&comp=list failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https:/xxxx.blob.core.windows.net/?include=metadata&comp=list failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (/Users/xxxxx/Desktop/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/node-fetch/lib/index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

Tried following the steps given in the below link to add the certificate but still no luck.

https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-self-signed-certificate-in-certificate-chain-and-similar-errors

Kindly let us know how to fix this issue

### Steps to Reproduce

1. Launch Microsoft explorer
2. Select the storage account
3. select container
4. Nothing gets listed from the container

![Uploading azureexlporererror.png…]()

### Actual Experience

![azureexlporererror](https://user-images.githubusercontent.com/64200262/121231571-2c6ae600-c8ae-11eb-876e-34df329cdd2c.png)

**Comment by ashfaq-rakuten** [comment]
This issue is fixed , It was due to firewall in our organisation.
