### ISSUE TITLE
Unable to authenticate in Azure Storage Explorer

### ISSUE THREAD

**Issue by JeffElliott1** [microsoft/AzureStorageExplorer#4730]
The following message appears when attempting to authenticate.  Other users with same group are able to authenticate from other devices.

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"unable to get local issuer certificate\\\",\\n  \\\"stack\\\": \\\"Error: unable to get local issuer certificate\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)\\\\n    at TLSSocket.emit (events.js:310:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:927:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)\\\",\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n}\""
}

**Comment by JeffElliott1** [comment]
Issue has been resolved.  Proxy is involved and needed to use proxy settings in Storage Explorer.
