### ISSUE TITLE
Issue in connecting to local blob

### ISSUE THREAD

**Issue by sunil-sap** [microsoft/AzureStorageExplorer#4889]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Platform

macOS

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000",
  "stack": "FetchError: request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at ClientRequest.<anonymous> (/private/var/folders/zc/08jbmbrx1klb6tcfv7knjw_80000gn/T/AppTranslocation/5B3D7B3F-A086-4BB6-A673-23924AC23981/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/node-fetch/lib/index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketErrorListener (_http_client.js:426:9)\n    at Socket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

### Steps to Reproduce

Trying connecting to local blob.

### Actual Experience

Version: 1.20.1
AzCopy Version: 10.11.0

Platform: macOS
Architecture: x64 
Build Number: 20210720.10 
Commit: e55de1ffc 
Support ID: c68c813d-8363-4882-dc91-81a683941866 

Copyright © 2021 Microsoft. All rights reserved.

### Additional Context

Version: 1.20.1
AzCopy Version: 10.11.0

Platform: macOS
Architecture: x64 
Build Number: 20210720.10 
Commit: e55de1ffc 
Support ID: c68c813d-8363-4882-dc91-81a683941866 

Copyright © 2021 Microsoft. All rights reserved.

**Comment by MRayermannMSFT** [comment]
@sunil-sap the error you have shared indicates that you are trying to access your emulator. For that, please make sure your emulator is installed and is running. Storage Explorer neither ships with an emulator nor does it start any emulators for you.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we suggest:
- Try all recommended solutions from above.
- If those do not work, you can open an Azure support ticket from the portal.
- Alternatively you can open a new issue here.
