### ISSUE TITLE
Azure Blob IoT behind proxy - SSL Certificate has expired

### ISSUE THREAD

**Issue by skywalkerisnull** [microsoft/AzureStorageExplorer#5012]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Architecture

x64

### Storage Explorer Build Number

202010924.14

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Connect to a Blob IoT that is behind a proxy server. 

In this instance, the Azure Blob IoT is behind a proxy server ([Traefik](https://traefik.io/)) on port 443. When we connect it says that the certificate has expired (screen shot of the certificate from the proxy attached for the same domain name)

But I can connect to it directly via the IP address and port 11005 without an issue.

```json
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://blob.blob.custom.com/account?comp=list&include=metadata failed, reason: certificate has expired",
  "stack": "FetchError: request to https://blob.blob.custom.com/account?comp=list&include=metadata failed, reason: certificate has expired\n    at ClientRequest.<anonymous> (C:\\Users\\AshleyWalker\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "CERT_HAS_EXPIRED",
  "code": "CERT_HAS_EXPIRED"
}
```

![image](https://user-images.githubusercontent.com/7260106/135993680-14919346-cec1-4980-9c27-45620c31cf31.png)

### Steps to Reproduce

1. Launch storage explorer
2. Connect to Azure Blob IoT (that is behind a proxy)
3. Get error message

### Actual Experience

Error message above

### Expected Experience

Connect to the storage as the SSL certificate is not expired.

**Comment by skywalkerisnull** [comment]
In addition, I have attempted to import the root certificates (incase NodeJS did not have them, or had expired versions)

**Comment by skywalkerisnull** [comment]
Further to this, here is a stackoverflow that seems to show that the internal version of node needs to be bumped: https://stackoverflow.com/a/69403683/11929735

**Comment by skywalkerisnull** [comment]
@MRayermannMSFT I have switched to using the system proxy (preview) option, and it now connects without any complaints of the SSL validity.

Thank you :)
