### ISSUE TITLE
Unable to open file dialog when uploading blobs or files

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#5230]
A user is unable to open the file/folder dialog when uploading blobs or files. This requires opening an Open File/Folder dialog. For other situations such as downloading, which requires a Save File/Folder dialog, the problem does not reproduce.

The user works in a tightly controlled work environment, so it's likely some administrative policies are blocking the behavior of certain Electron APIs. The problem does not reproduce when the user is logged in as a local admin, or in a standard VM when logged in as a basic user.

After debugging with the user, we discovered that an uncaught error is thrown when attempting to call `remote.app.getPath("documents")`:

> Error: Could not call remote method 'getPath'. Check that the method signature is correct. Underlying error: Failed to get 'documents' path Underlying stack: Error: Failed to get 'documents' path at electron/js2c/browser_init.js:213:7853 at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4254) at IpcMainImpl.emit (events.js:310:20) at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8961) at WebContents.emit (events.js:310:20) at electron/js2c/browser_init.js:213:7881 at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4254) at IpcMainImpl.emit (events.js:310:20) at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8961) at WebContents.emit (events.js:310:20)

It should be noted that for the Save File/Folder dialog, we retrieve the user's "Downloads" path, which does not throw an error like the one above for the user.

The problem and potential solutions could consist of one or more of the following:
- Use of `remote.app.getPath()` in the renderer process fails due to system restrictions. The code attempting to open the dialog should be moved to the main process.
- Access to the user's "Documents" is restricted. The code should be surrounded by a try/catch block and use a default path instead (like the user's home directory).

**Comment by craxal** [comment]
Customer reported back to let us know that the fix we let him test worked for him.
