### ISSUE TITLE
Unable to create new queue locally in Azure Storage Explorer

### ISSUE THREAD

**Issue by srilalfonseka-bond** [microsoft/AzureStorageExplorer#5306]
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10001/devstoreaccount1/testq3?timeout=30 failed, reason: connect ECONNREFUSED 127.0.0.1:10001",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED",
  "stack": "FetchError: request to http://127.0.0.1:10001/devstoreaccount1/testq3?timeout=30 failed, reason: connect ECONNREFUSED 127.0.0.1:10001\n    at ClientRequest.<anonymous> (C:\\Users\\Sriral.Fonseka\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at Socket.socketErrorListener (_http_client.js:469:9)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}

**Comment by srilalfonseka-bond** [comment]
Got it resolved. I needed to start Windows Azure Storage Emulator.
