### ISSUE TITLE
Unable to retrieve child resources from blob container

### ISSUE THREAD

**Issue by jamescullis1** [microsoft/AzureStorageExplorer#5458]
I can't access any blob containers either through the Azure portal in a browser or through the Azure Storage Explorer.

I get the following error message:

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://lexnetworkdocdirect.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 20.38.107.4:443",
  "stack": "FetchError: request to https://lexnetworkdocdirect.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 20.38.107.4:443\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

**Comment by jamescullis1** [comment]
Appears to all be accessible again...
