### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by f1zb4n72** [microsoft/AzureStorageExplorer#5647]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Storage Explorer Build Number

20220406.1

### Platform

Linux (snap)

### OS Version

Linux Mint 20.2

### Bug Description

I connected the application with a customer key, in his server I can see all tree, but on my PC I have a "not found" error browsing the tree.

This is the log:
[azure_trace.log](https://github.com/microsoft/AzureStorageExplorer/files/8532151/azure_trace.log)

Many thanks
Luca

### Steps to Reproduce

1. Launch Storage Explorer 
2. Expand a blob container node

### Actual Experience

When I browse the tree I have an ENOTFOUND error popup

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "request to https://xxx.blob.core.windows.net/?comp=list&include=metadata failed, reason: getaddrinfo ENOTFOUND xxx.blob.core.windows.net",
  "stack": "RestError: request to https://xxx.blob.core.windows.net/?comp=list&include=metadata failed, reason: getaddrinfo ENOTFOUND xxx.blob.core.windows.net\n    at NodeFetchHttpClient.sendRequest (/snap/storage-explorer/33/resources/app/node_modules/@azure/core-http/dist/index.js:2670:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CoreHttpLogHttpClient.sendRequest (/snap/storage-explorer/33/resources/app/node_modules/@storage-explorer/azure-sdk-helpers/dist/src/HttpClients/CoreHttpLogHttpClient.js:31:34)\n    at async StorageRetryPolicy.attemptSendRequest (/snap/storage-explorer/33/resources/app/node_modules/se-blob-extension/node_modules/@azure/storage-blob/dist/index.js:14086:24)\n    at async StorageClientContext.sendOperationRequest (/snap/storage-explorer/33/resources/app/node_modules/@azure/core-http/dist/index.js:4934:31)\n    at async BlobServiceClient.listContainersSegment (/snap/storage-explorer/33/resources/app/node_modules/se-blob-extension/node_modules/@azure/storage-blob/dist/index.js:23132:20)",
  "code": "REQUEST_SEND_ERROR",
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://xxx.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-10-02"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer, 1.23.1, linux azsdk-js-storageblob/12.8.0 (NODE-VERSION v16.9.1; Linux 5.4.0-109-generic)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "5c37dfe7-d4e6-4901-a679-04e169af8767"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Thu, 21 Apr 2022 14:46:05 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "Signed SharedKey Redacted="
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "5c37dfe7-d4e6-4901-a679-04e169af8767",

**Comment by agrewal097** [comment]
how can we fix this ?

**Comment by f1zb4n72** [comment]
Hi,
tell me why I can browse the tree on a Windows machine, but I can't on my Linux machine even when I put the same key.
It seems to me a bug of the Linux version of storage-explore, so I reported to community, but if you think it's not, close the thread.

Bye

**Comment by MRayermannMSFT** [comment]
@f1zb4n72 can you try enabling System Proxy? Go to settings (gear on the left) -> application -> proxy, and then change the dropdown to "System Proxy (Preview)".

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening an Azure support ticket from the portal. You can also open a new issue here.
