### ISSUE TITLE
RestError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature

### ISSUE THREAD

**Issue by arunthekkemadam** [microsoft/AzureStorageExplorer#6229]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.1

### Architecture

i86

### Storage Explorer Build Number

20220510.2

### Platform

Windows

### OS Version

Windows10

### Bug Description

{
  "name": "RestError",
  "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:4ee1f5b1-3002-0047-23fd-eb8fdf000000\nTime:2022-10-30T01:20:38.8944386Z",
  "stack": "RestError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:4ee1f5b1-3002-0047-23fd-eb8fdf000000\nTime:2022-10-30T01:20:38.8944386Z\n    at handleBodyError (C:\\Users\\50531505\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:4053:11)\n    at parseTransactionResponse (C:\\Users\\50531505\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:4008:9)\n    at C:\\Users\\50531505\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:3989:20\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.withSpan (C:\\Users\\50531505\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\node_modules\\@azure\\core-tracing\\dist\\index.js:145:28)\n    at async TableClient.#batchEntities (C:\\Users\\50531505\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Clients\\TableClient.js:191:17)\n    at async TableClient.runOperation (C:\\Users\\50531505\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\azure-sdk-helpers\\dist\\src\\CoreRest\\CoreRestClient.js:107:24)\n    at async C:\\Users\\50531505\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Actions\\TableActions.js:62:9\n    at async Promise.all (index 5207)\n    at async Object.deleteEntities (C:\\Users\\50531505\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Actions\\TableActions.js:66:9)",
  "code": "AuthenticationFailed",
  "statusCode": 403,
  "request": {
    "url": "https://xxxx.table.core.windows.net/$batch",
    "body": "--batch_c0f92a65-9fec-45d5-87e3-26b12db756a1\r\ncontent-type: multipart/mixed; boundary=changeset_8e1fc0e1-8bbd-48d7-9263-d70b358a131d\r\n\r\n\r\n--changeset_8e1fc0e1-8bbd-48d7-9263-d70b358a131d\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE https://xxxx.table.core.windows.net/xxxxActivityTable(PartitionKey='636205316082348221',RowKey='xxxxScan__xxxxScan_IN_0__xxxxActivityTable__2cc4cb4f-838b-4949-b24f-006739155f75') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_8e1fc0e1-8bbd-48d7-9263-d70b358a131d--\r\n--batch_c0f92a65-9fec-45d5-87e3-26b12db756a1--\r\n",
    "headers": {
      "accept": "application/json",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0;",
      "maxdataserviceversion": "3.0;NetFx",
      "content-type": "multipart/mixed; boundary=batch_c0f92a65-9fec-45d5-87e3-26b12db756a1",
      "accept-charset": "UTF-8",
      "connection": "Keep-Alive",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.24.1 (win32) azsdk-js-data-tables/13.1.1 core-rest-pipeline/1.8.0 Node/v16.13.2 OS/(ia32-Windows_NT-10.0.19044)",
      "x-ms-client-request-id": "bb5ed42f-929e-41f2-8190-f98970ab8650",
      "authorization": "Bearer JSON Web Token Redacted",
      "content-length": "653"
    },
    "method": "POST",
    "timeout": 0,
    "disableKeepAlive": false,
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "bb5ed42f-929e-41f2-8190-f98970ab8650",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "status": 403,
    "headers": {
      "content-length": "299",
      "content-type": "application/json",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "4ee1f5b1-3002-0047-23fd-eb8fdf000000",
      "x-ms-error-code": "AuthenticationFailed",
      "date": "Sun, 30 Oct 2022 01:20:38 GMT"
    },
    "request": {
      "url": "https://xxxx.table.core.windows.net/$batch",
      "body": "--batch_c0f92a65-9fec-45d5-87e3-26b12db756a1\r\ncontent-type: multipart/mixed; boundary=changeset_8e1fc0e1-8bbd-48d7-9263-d70b358a131d\r\n\r\n\r\n--changeset_8e1fc0e1-8bbd-48d7-9263-d70b358a131d\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE https://xxxx.table.core.windows.net/xxxxActivityTable(PartitionKey='636205316082348221',RowKey='xxxxScan__xxxxScan_IN_0__xxxxActivityTable__2cc4cb4f-838b-4949-b24f-006739155f75') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_8e1fc0e1-8bbd-48d7-9263-d70b358a131d--\r\n--batch_c0f92a65-9fec-45d5-87e3-26b12db756a1--\r\n",
      "headers": {
        "accept": "application/json",
        "x-ms-version": "2019-02-02",
        "dataserviceversion": "3.0;",
        "maxdataserviceversion": "3.0;NetFx",
        "content-type": "multipart/mixed; boundary=batch_c0f92a65-9fec-45d5-87e3-26b12db756a1",
        "accept-charset": "UTF-8",
        "connection": "Keep-Alive",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer/1.24.1 (win32) azsdk-js-data-tables/13.1.1 core-rest-pipeline/1.8.0 Node/v16.13.2 OS/(ia32-Windows_NT-10.0.19044)",
        "x-ms-client-request-id": "bb5ed42f-929e-41f2-8190-f98970ab8650",
        "authorization": "Bearer JSON Web Token Redacted",
        "content-length": "653"
      },
      "method": "POST",
      "timeout": 0,
      "disableKeepAlive": false,
      "withCredentials": false,
      "tracingOptions": {
        "tracingContext": {
          "_contextMap": {}
        }
      },
      "requestId": "bb5ed42f-929e-41f2-8190-f98970ab8650",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "bodyAsText": "{\"odata.error\":{\"code\":\"AuthenticationFailed\",\"message\":{\"lang\":\"en-US\",\"value\":\"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:4ee1f5b1-3002-0047-23fd-eb8fdf000000\\nTime:2022-10-30T01:20:38.8944386Z\"}}}",
    "parsedBody": {
      "odata.error": {
        "code": "AuthenticationFailed",
        "message": {
          "lang": "en-US",
          "value": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:4ee1f5b1-3002-0047-23fd-eb8fdf000000\nTime:2022-10-30T01:20:38.8944386Z"
        }
      }
    }
  }
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Open the table from the Blob container
3. Tried to delete the selected 14000 entries and got the error that 11408 only got deleted.

### Actual Experience

![image](https://user-images.githubusercontent.com/116986671/198858859-5b03ad75-301c-4485-88ba-bef20c11a43a.png)

### Expected Experience

Deleted all the seleted entries

**Comment by MRayermannMSFT** [comment]
@arunthekkemadam 
1. Any idea about how long Storage Explorer was deleting entities for?
2. If you try to delete the remaining entities is Storage Explorer able to delete them?
3. Can you:
   1. Go to Settings (gear on the left) > Application > Logging > Log Level, and choose "Debug" in the dropdown
   2. Restart Storage Explorer
   4. And then if the error ever happens again....
   5. Go to Help > Open Logs Directory
   6. In the file explorer window, go to the newest folder
   7. Zip up all the files
   8. Upload the zip here

**Comment by arunthekkemadam** [comment]
@MRayermannMSFT 

1) For the deletion request of 5000 entries the storage explorer took around 3 minutes and 3854 of 5000 got deleted.
2) Yes. 
3) Uploaded.
[2022-11-01_135945.zip](https://github.com/microsoft/AzureStorageExplorer/files/9908239/2022-11-01_135945.zip)

**Comment by craxal** [comment]
@arunthekkemadam Did the entities you were trying to delete have different partition keys? Did some partitions contain more than 100 entities?

**Comment by craxal** [comment]
Closing due to inactivity. If this is still an issue, please reply with the info requested previously, and we will review.
