### ISSUE TITLE
xterm redirection needs to be left on

### ISSUE THREAD

**Issue by gidipas** [microsoft/AzureStorageExplorer#6531]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Synopsys (customer) is trying to launch storage explorer from a Citrix terminal to a linux desktop.

### Desired Solution

Linux Storage explorer redirect and launch in a Citirx terminal of a Linux client.

### Additional Context

Synopsys has launched a SaaS platform on Azure for ite EDA customer to utilize Synopsys tools as a service. First step is data transfer into Azure and it is proving cumbersome to move data in blob containers.  they are trying to use Linux version of storage explorer for their customers to ease the use.  the azcopy cli is cumbersome and not intuitive enough for a service.  I can get the customer on a call for more specific details.  see TrackingID# 2201210010001953 for more specifics of troubleshooting.

**Comment by gidipas** [comment]
Relevant message on failure:

evalpv6@edprj316-submit storageexplorer]$ StorageExplorer --disablble-extensions -disable-gpu
[2023-01-24T18:06:40.528Z] (main:5504) <NONE> Log file: /remote/usrhome/evalpv6/.config/StorageExplorer/logs/2023-01-24_100640/2023-01-24_100640_main_5504.log
[2023-01-24T18:06:40.531Z] (main:5504) <NONE> Log level: info
[2023-01-24T18:06:40.531Z] (main:5504) <INFO> Startup app state:  {
    lastWindowState: { rect: { x: 0, y: 0, width: 1000, height: 768 }, maximized: false },
    disableGpu: false,
    dialogAutoResponse: {}
  }
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /remote/usrhome/evalpv6/bin/storageexplorer/resources/app/node_modules/keytar/build/Release/keytar.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1252:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1810)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Function.load [as _load] (/remote/usrhome/evalpv6/bin/storageexplorer/resources/app/out/app/SdkLoading/SdkRequireInterceptor.js:28:37)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/remote/usrhome/evalpv6/bin/storageexplorer/resources/app/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1167:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1222:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Function.load [as _load] (/remote/usrhome/evalpv6/bin/storageexplorer/resources/app/out/app/SdkLoading/SdkRequireInterceptor.js:28:37)
[5504:0124/100641.013432:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[5504:0124/100641.013849:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

**Comment by gidipas** [comment]
@MRayermannMSFT i believe they are using the tar.gz.  I am pretty certain they stepped through the troubleshooting steps with MSFT support.  MSFT support has deferred back to the product team.  If you can, please refer to the case notes.  that should detail the steps already taken.  I am opening this case for the customer, but I am not specifically hands on with the product since it is in their subscription.  I will be glad to facilitate an email chain to provide the full details.  FYI, it is a production blocker for the customer at the moment.

**Comment by MRayermannMSFT** [comment]
@gidipas no I don't have any updates. I'm still waiting for more explanation on why there is a belief that this is an issue with xterm when there is a clear error about something else, which doesn't sound to be xterm related. I don't have access to any sort of case notes or anything like that.

**Comment by gidipas** [comment]
Hi Matthew,

Thanks for the response.  I apologize, I assumed you would have access to tools when they were related to your product.  I have sent an ask back to the customer for more specifics.  I trust that the customer has already run down most of these, but I will ask for clarification on what that error is for and more specifics of how Storage Explorer is being deployed.

**Comment by gidipas** [comment]
Hi Matthew,

As I suspected, the error message is spurious and unrelated. They have examples both with and without the error and the forwarding problem persists.  Attached you will find annotated case notes.  It appears you worked on this case previously.  We can surmise that Synopsys is asking to see if any progress has been made to address the issue from that previous case.

Can we support the ask?  We would like to provide an update on if this has been reviewed and is possible or should we try to find an alternative?

Look forward to your thoughts.  We can also facilitate a call with the customer for more information if you would like.  Let us know.

Best,

Gi
From: Giancarlo DiPasquale
Sent: Thursday, February 23, 2023 4:40 PM
To: microsoft/AzureStorageExplorer ***@***.***>; microsoft/AzureStorageExplorer ***@***.***>
Cc: Mention ***@***.***>; Damian Hasak ***@***.***>; Patrick Gary ***@***.***>
Subject: RE: [microsoft/AzureStorageExplorer] xterm redirection needs to be left on (Issue #6531)

Hi Matthew,

Thanks for the response.  I apologize, I assumed you would have access to tools when they were related to your product.  I have sent an ask back to the customer for more specifics.  I trust that the customer has already run down most of these, but I will ask for clarification on what that error is for and more specifics of how Storage Explorer is being deployed.

**Comment by MRayermannMSFT** [comment]
@gidipas if you're responding to GitHub via email you cannot attach things to your email. You have to come to GitHub to add attachments. Feel free to also just reach out over teams.

**Comment by MRayermannMSFT** [comment]
Please pass on these links to the customer to see if they are of any help. The first and second seem especially promising.

- https://github.com/microsoft/vscode/issues/137850
- https://github.com/atom/node-keytar/issues/132
- https://github.com/Noovolari/leapp/issues/153

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
