### ISSUE TITLE
App crashes and quits immediatly

### ISSUE THREAD

**Issue by YusufMavzer** [microsoft/AzureStorageExplorer#7405]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2

### Architecture

x64

### Platform

Linux (tar.gz)

### OS Version

Fedora 38

### Bug Description

I tried Azure Storage Explorer for the first time. 
Downloaded it and launch it.

It wants me to signin to an azure via the browser that it launch.
But it didn't launch any browser or opened up a page. 
It also doesn't say which URL. Because if it isn't able to open the page by itself. Why don't I do it instead.

If I wait the prompt out it tells me to try another option.
Well I have a Azurite docker container. I fill in the credentials and voila
It crashes immediatly. It works in on Windows with the same container.

```
[2023-10-13T09:53:00.844Z] (blob-extension:285642) <ERRO> HttpClient threw while making API call for BlobService.getAccountInfo
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 0b97cef3-eec6-4584-b016-547b19305f37, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{"cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":10000}},"code":"ECONNREFUSED","errno":-111}
[2023-10-13T09:53:00.849Z] (blob-extension:285642) <INFO> API call for BlobService.getAccountInfo succeeded
  GET http://127.0.0.1:19900/devstoreaccount1?comp=properties&restype=account - 200
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 2927cd53-cc86-423f-bfea-c6ae5bbf3b7c, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2021-10-04, ProxySettings: undefined
[2023-10-13T09:53:00.853Z] (blob-extension:285642) <INFO> API call for BlobService.getAccountInfo succeeded
  GET http://127.0.0.1:19900/devstoreaccount1?comp=properties&restype=account - 200
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: becfd02d-1a94-4869-9d2d-b3252f3a5e51, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2021-10-04, ProxySettings: undefined
[2023-10-13T09:53:00.853Z] (blob-extension:285642) <INFO> API call for BlobService.getAccountInfo succeeded
  GET http://127.0.0.1:19900/devstoreaccount1?comp=properties&restype=account - 200
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: acdfad5c-01d7-4663-919b-0e1861688668, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2021-10-04, ProxySettings: undefined
[2023-10-13T09:53:00.857Z] (blob-extension:285642) <ERRO> HttpClient threw while making API call for BlobService.getAccountInfo
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 0b97cef3-eec6-4584-b016-547b19305f37, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{"cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":10000}},"code":"ECONNREFUSED","errno":-111}
[2023-10-13T09:53:04.870Z] (blob-extension:285642) <ERRO> HttpClient threw while making API call for BlobService.getAccountInfo
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 0b97cef3-eec6-4584-b016-547b19305f37, Date sent: Fri, 13 Oct 2023 09:53:04 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{"cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":10000}},"code":"ECONNREFUSED","errno":-111}
[2023-10-13T09:53:16.894Z] (blob-extension:285642) <ERRO> HttpClient threw while making API call for BlobService.getAccountInfo
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 0b97cef3-eec6-4584-b016-547b19305f37, Date sent: Fri, 13 Oct 2023 09:53:16 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{"cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":10000}},"code":"ECONNREFUSED","errno":-111}
```

![image](https://github.com/microsoft/AzureStorageExplorer/assets/28507059/7185ec6d-4208-46a8-9ad5-c2da5d4c214e)

### Steps to Reproduce

1. Download latest version. On linux
2. Make sure your linux has no Azure signin other azure apps whats so ever. Make it clean vanilla as possible
3. try to run it

### Actual Experience

I tried Azure Storage Explorer for the first time. 
Downloaded it and launch it.

It wants me to signin to an azure via the browser that it launch.
But it didn't launch any browser or opened up a page. 
It also doesn't say which URL. Because if it isn't able to open the page by itself. Why don't I do it instead.

If I wait the prompt out it tells me to try another option.
Well I have a Azurite docker container. I fill in the credentials and voila
It crashes immediatly. It works in on Windows with the same container.

### Expected Experience

Launch the browser for me to signin
Or provide a URL that I can manually do it myself
Or work without requiring to sign in (for emulator use only)

**Comment by YusufMavzer** [comment]
`[2023-10-13T09:53:00.543Z] (blob-extension:285642) <NONE> Log level: info
[2023-10-13T09:53:00.571Z] (blob-extension:285642) <INFO> Loading SSL Settings
[2023-10-13T09:53:00.571Z] (blob-extension:285642) <INFO> Injecting certs found in /home/yusuf/.config/StorageExplorer/certs/
[2023-10-13T09:53:00.572Z] (blob-extension:285642) <INFO> Sending init acks back to parent process
[2023-10-13T09:53:00.844Z] (blob-extension:285642) <ERRO> HttpClient threw while making API call for BlobService.getAccountInfo
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 0b97cef3-eec6-4584-b016-547b19305f37, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{"cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":10000}},"code":"ECONNREFUSED","errno":-111}
[2023-10-13T09:53:00.849Z] (blob-extension:285642) <INFO> API call for BlobService.getAccountInfo succeeded
  GET http://127.0.0.1:19900/devstoreaccount1?comp=properties&restype=account - 200
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 2927cd53-cc86-423f-bfea-c6ae5bbf3b7c, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2021-10-04, ProxySettings: undefined
[2023-10-13T09:53:00.853Z] (blob-extension:285642) <INFO> API call for BlobService.getAccountInfo succeeded
  GET http://127.0.0.1:19900/devstoreaccount1?comp=properties&restype=account - 200
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: becfd02d-1a94-4869-9d2d-b3252f3a5e51, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2021-10-04, ProxySettings: undefined
[2023-10-13T09:53:00.853Z] (blob-extension:285642) <INFO> API call for BlobService.getAccountInfo succeeded
  GET http://127.0.0.1:19900/devstoreaccount1?comp=properties&restype=account - 200
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: acdfad5c-01d7-4663-919b-0e1861688668, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2021-10-04, ProxySettings: undefined
[2023-10-13T09:53:00.857Z] (blob-extension:285642) <ERRO> HttpClient threw while making API call for BlobService.getAccountInfo
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 0b97cef3-eec6-4584-b016-547b19305f37, Date sent: Fri, 13 Oct 2023 09:53:00 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{"cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":10000}},"code":"ECONNREFUSED","errno":-111}
[2023-10-13T09:53:04.870Z] (blob-extension:285642) <ERRO> HttpClient threw while making API call for BlobService.getAccountInfo
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 0b97cef3-eec6-4584-b016-547b19305f37, Date sent: Fri, 13 Oct 2023 09:53:04 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{"cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":10000}},"code":"ECONNREFUSED","errno":-111}
[2023-10-13T09:53:16.894Z] (blob-extension:285642) <ERRO> HttpClient threw while making API call for BlobService.getAccountInfo
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 0b97cef3-eec6-4584-b016-547b19305f37, Date sent: Fri, 13 Oct 2023 09:53:16 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{"cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":10000}},"code":"ECONNREFUSED","errno":-111}
`

**Comment by craxal** [comment]
@YusufMavzer Are you trying to connect to Azure or to the Azurite emulator? If the emulator, there should be no need to sign in or authenticate. You will also need to configure the ports for the Docker container running Azurite so your system knows to forward network communications to the Docker container.

Just double-checking, have you looked through the [troubleshooting guide](https://learn.microsoft.com/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows) to see if anything there helps?

Using the .tar.gz distribution can be tricky, especially on Linux systems we don't officially support, because it does not come bundled with the necessary dependencies. Have you tried using the [snap distribution](https://snapcraft.io/storage-explorer)?

If you really need the .tar.gz, you'll need to make sure you install the necessary dependencies (or the Fedora equivalents). Make sure that includes .NET 6, because the error message you got suggests .NET 6 might be missing from your system.

**Comment by YusufMavzer** [comment]
I posted a showing the bug screenrecording. 

All I want is to use the emulator. I don't want to sign in. 
I have dotnet 6 runetime & sdk installed on my machine and am running azurite running in docker container. 

The signin thing was my last resort but that didn't even work. It gave a message telling me my browser should be launched with a signin page but no browser or page was opened

https://vimeo.com/874518761?share=copy

**Comment by YusufMavzer** [comment]
These are logs from that video

```
./StorageExplorerExe 
[2023-10-15T13:38:39.818Z] (main:897389) <NONE> Log file: /home/yusuf/.config/StorageExplorer/logs/2023-10-15_153839/2023-10-15_153839_main_897389.log
[2023-10-15T13:38:39.823Z] (main:897389) <NONE> Log level: info
[2023-10-15T13:38:39.823Z] (main:897389) <INFO> Startup app state:  {
    lastWindowState: { rect: { x: 0, y: 0, width: 1000, height: 768 }, maximized: false },
    disableGpu: false,
    dialogAutoResponse: {}
  }
[2023-10-15T13:38:40.427Z] (main:897389) <INFO> No proxy environment variables exist on startup
[2023-10-15T13:38:40.428Z] (main:897389) <INFO> Applying proxy configuration
[2023-10-15T13:38:40.429Z] (main:897389) <INFO> Proxy configuration source set to: none
[2023-10-15T13:38:40.429Z] (main:897389) <INFO> Proxy configuration set to: undefined
[2023-10-15T13:38:40.431Z] (main:897389) <INFO> Initializing user accounts manager account store...
[2023-10-15T13:38:40.640Z] (main:897389) <ERRO> IdentityUserAccountsManager._initAccountStore failed to finish: Error: Hub Controller process exited prematurely with exit code 131.
      at ControllerConnection.onControllerProcessExited (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:134:21)
      at ChildProcess.<anonymous> (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:88:76)
      at Object.onceWrapper (node:events:628:26)
      at ChildProcess.emit (node:events:525:35)
      at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
    exitCode: 131
  }
[2023-10-15T13:38:40.642Z] (main:897389) <INFO> Retrying user accounts manager account store initialization in 5 seconds...
[2023-10-15T13:38:41.375Z] (main:897389) <WARN> An implementation of 'Environment.Theming.onThemeChanged' has already been registered by another provider, this most recent implementation will be ignored unless 'Environment.Theming.onThemeChanged is used as an event'.
[2023-10-15T13:38:41.375Z] (main:897389) <WARN> An implementation of 'Environment.Zoom.onZoomChanged' has already been registered by another provider, this most recent implementation will be ignored unless 'Environment.Zoom.onZoomChanged is used as an event'.
[2023-10-15T13:38:41.375Z] (main:897389) <WARN> An implementation of 'ActivityManager.onExecuteActionEvent' has already been registered by another provider, this most recent implementation will be ignored unless 'ActivityManager.onExecuteActionEvent is used as an event'.
[2023-10-15T13:38:41.376Z] (main:897389) <INFO> Initializing extension manager...
[2023-10-15T13:38:41.377Z] (main:897389) <INFO> Done looking for extensions to open or debug.
[2023-10-15T13:38:41.380Z] (main:897389) <INFO> Loading 16 extensions
[2023-10-15T13:38:41.494Z] (main:897389) <INFO> Extensions loaded
[2023-10-15T13:38:41.835Z] (main:897389) <INFO> SubscriptionCache found no valid cache, returning empty object.
[2023-10-15T13:38:42.131Z] (start-panel:897575) <NONE> Log file: /home/yusuf/.config/StorageExplorer/logs/2023-10-15_153839/2023-10-15_153839_start-panel_897575.log
[2023-10-15T13:38:42.134Z] (start-panel:897575) <NONE> Log level: info
[2023-10-15T13:38:42.166Z] (start-panel:897575) <INFO> Loading SSL Settings
[2023-10-15T13:38:42.166Z] (start-panel:897575) <INFO> Injecting certs found in /home/yusuf/.config/StorageExplorer/certs/
[2023-10-15T13:38:42.167Z] (start-panel:897575) <INFO> Sending init acks back to parent process
[2023-10-15T13:38:42.371Z] (main:897389) <INFO> AzureSubscriptionsManager checking for new accounts...
[2023-10-15T13:38:45.642Z] (main:897389) <INFO> Initializing user accounts manager account store...
[2023-10-15T13:38:45.776Z] (main:897389) <ERRO> IdentityUserAccountsManager._initAccountStore failed to finish: Error: Hub Controller process exited prematurely with exit code 131.
      at ControllerConnection.onControllerProcessExited (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:134:21)
      at ChildProcess.<anonymous> (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:88:76)
      at Object.onceWrapper (node:events:628:26)
      at ChildProcess.emit (node:events:525:35)
      at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
    exitCode: 131
  }
[2023-10-15T13:38:45.776Z] (main:897389) <INFO> Retrying user accounts manager account store initialization in 5 seconds...
[2023-10-15T13:38:50.778Z] (main:897389) <INFO> Initializing user accounts manager account store...
[2023-10-15T13:38:50.907Z] (main:897389) <ERRO> IdentityUserAccountsManager._initAccountStore failed to finish: Error: Hub Controller process exited prematurely with exit code 131.
      at ControllerConnection.onControllerProcessExited (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:134:21)
      at ChildProcess.<anonymous> (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:88:76)
      at Object.onceWrapper (node:events:628:26)
      at ChildProcess.emit (node:events:525:35)
      at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
    exitCode: 131
  }
[2023-10-15T13:38:50.907Z] (main:897389) <INFO> Retrying user accounts manager account store initialization in 5 seconds...
[2023-10-15T13:38:55.908Z] (main:897389) <INFO> Initializing user accounts manager account store...
[2023-10-15T13:38:56.035Z] (main:897389) <ERRO> IdentityUserAccountsManager._initAccountStore failed to finish: Error: Hub Controller process exited prematurely with exit code 131.
      at ControllerConnection.onControllerProcessExited (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:134:21)
      at ChildProcess.<anonymous> (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:88:76)
      at Object.onceWrapper (node:events:628:26)
      at ChildProcess.emit (node:events:525:35)
      at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
    exitCode: 131
  }
[2023-10-15T13:38:56.035Z] (main:897389) <INFO> Retrying user accounts manager account store initialization in 5 seconds...
[2023-10-15T13:38:58.251Z] (activity-log:897786) <NONE> Log file: /home/yusuf/.config/StorageExplorer/logs/2023-10-15_153839/2023-10-15_153839_activity-log_897786.log
[2023-10-15T13:38:58.254Z] (activity-log:897786) <NONE> Log level: info
[2023-10-15T13:38:58.277Z] (activity-log:897786) <INFO> Loading SSL Settings
[2023-10-15T13:38:58.277Z] (activity-log:897786) <INFO> Injecting certs found in /home/yusuf/.config/StorageExplorer/certs/
[2023-10-15T13:38:58.277Z] (activity-log:897786) <INFO> Sending init acks back to parent process
[2023-10-15T13:38:58.287Z] (activity-log:897786) <INFO> Activity added {
    title: 'Adding new connection...',
    message: '',
    speed: undefined,
    progress: undefined,
    status: 1,
    actions: []
  }
[2023-10-15T13:38:58.570Z] (storage-account-extension:897802) <NONE> Log file: /home/yusuf/.config/StorageExplorer/logs/2023-10-15_153839/2023-10-15_153839_storage-account-extension_897802.log
[2023-10-15T13:38:58.572Z] (storage-account-extension:897802) <NONE> Log level: info
[2023-10-15T13:38:58.596Z] (storage-account-extension:897802) <INFO> Loading SSL Settings
[2023-10-15T13:38:58.596Z] (storage-account-extension:897802) <INFO> Injecting certs found in /home/yusuf/.config/StorageExplorer/certs/
[2023-10-15T13:38:58.597Z] (storage-account-extension:897802) <INFO> Sending init acks back to parent process
[2023-10-15T13:39:01.036Z] (main:897389) <INFO> Initializing user accounts manager account store...
[2023-10-15T13:39:01.172Z] (main:897389) <ERRO> IdentityUserAccountsManager._initAccountStore failed to finish: Error: Hub Controller process exited prematurely with exit code 131.
      at ControllerConnection.onControllerProcessExited (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:134:21)
      at ChildProcess.<anonymous> (/home/yusuf/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:88:76)
      at Object.onceWrapper (node:events:628:26)
      at ChildProcess.emit (node:events:525:35)
      at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
    exitCode: 131
  }
[2023-10-15T13:39:01.188Z] (main:897389) <ERRO> UNHANDLED PROMISE REJECTION in main process:
  Error: Hub Controller process exited prematurely with exit code 131.
[2023-10-15T13:39:01.380Z] (activity-log:897786) <INFO> Activity finalized {
    title: 'Successfully added new connection.',
    message: '',
    speed: undefined,
    progress: undefined,
    status: 2,
    actions: []
  }
[2023-10-15T13:39:01.593Z] (blob-extension:897828) <NONE> Log file: /home/yusuf/.config/StorageExplorer/logs/2023-10-15_153839/2023-10-15_153839_blob-extension_897828.log
[2023-10-15T13:39:01.595Z] (blob-extension:897828) <NONE> Log level: info
[2023-10-15T13:39:01.620Z] (blob-extension:897828) <INFO> Loading SSL Settings
[2023-10-15T13:39:01.620Z] (blob-extension:897828) <INFO> Injecting certs found in /home/yusuf/.config/StorageExplorer/certs/
[2023-10-15T13:39:01.621Z] (blob-extension:897828) <INFO> Sending init acks back to parent process
[2023-10-15T13:39:01.901Z] (blob-extension:897828) <INFO> API call for BlobService.getAccountInfo succeeded
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account - 200
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 58acb76a-190d-49e6-bef2-f3325d080088, Date sent: Sun, 15 Oct 2023 13:39:01 GMT, ApiVersion: 2021-10-04, ProxySettings: undefined
[2023-10-15T13:39:01.906Z] (blob-extension:897828) <ERRO> API call for BlobService.getAccountInfo failed
  GET http://127.0.0.1:10000/devstoreaccount1?comp=properties&restype=account - 403
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 18a6235b-230f-417a-a969-5fdc43dceab8, Date sent: Sun, 15 Oct 2023 13:39:01 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  ErrorCode: AuthorizationFailure
[2023-10-15T13:39:01.911Z] (blob-extension:897828) <WARN> Fallback for operation 'BlobService.getAccountInfo, count 1
[2023-10-15T13:39:27.856Z] (main:897389) <INFO> Calling handleQuitOrRelaunch from quit
[2023-10-15T13:39:27.857Z] (main:897389) <INFO> Quitting, sessionEnded: false, force: true, quitOrRelaunch: quit
[2023-10-15T13:39:27.858Z] (main:897389) <INFO> Calling quit, bye!
```
`extractbundler.azurite | Azurite Blob service is starting at http://0.0.0.0:10000
extractbundler.azurite | Azurite Blob service is successfully listening at http://0.0.0.0:10000
extractbundler.azurite | Azurite Queue service is starting at http://0.0.0.0:10001
extractbundler.azurite | Azurite Queue service is successfully listening at http://0.0.0.0:10001
extractbundler.azurite | Azurite Table service is starting at http://0.0.0.0:10002
extractbundler.azurite | Azurite Table service is successfully listening at http://0.0.0.0:10002
extractbundler.azurite | 172.31.0.1 - - [15/Oct/2023:13:36:19 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 403 -
extractbundler.azurite | 172.31.0.1 - - [15/Oct/2023:13:36:19 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 403 -
extractbundler.azurite | 172.31.0.1 - - [15/Oct/2023:13:39:01 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 200 -
extractbundler.azurite | 172.31.0.1 - - [15/Oct/2023:13:39:01 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 403 -
`

**Comment by craxal** [comment]
@YusufMavzer The error message your seeing is not the result of Storage Explorer trying to sign in. It's merely reporting that the component used for sign in was not able to start. This usually happens when Storage Explorer can't find a .NET installation. Fixing this should not be necessary to connect to an emulator. To help resolve this, we highly recommend you [install the snap](https://snapcraft.io/install/storage-explorer/fedora), which is easy to do on Fedora.

Have you mapped your host machine's port to the Azurite container's port? The request is likely failing because there's nothing actually listening at 127.0.0.1:10000. Azurite is listening at 0.0.0.0:10000 (in the container). In order to forward requests to the container, you need to publish the container's ports at least to the host (pulled from https://hub.docker.com/_/microsoft-azure-storage-azurite):

```
docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite
```

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please contact Azure support, or open a new issue, if you still need help.

**Comment by AndreRicardo-Zoetis** [comment]
> To help resolve this, we highly recommend you [install the snap](https://snapcraft.io/install/storage-explorer/fedora), which is easy to do on Fedora.

I had a similar issue in Ubuntu 22.04 also crashed with the error "The authentication library used by Storage Explorer has failed to start properly."
Installing the snap and then running the `snap connect storage-explorer:password-manager-service :password-manager-service` allowed me to connect to Azurite.

The error on the StorageExplorer-linux-x64.tar.gz version:

```sh
[2023-12-11T12:32:24.879Z] (main:283440) <INFO> Retrying user accounts manager account store initialization in 5 seconds...
[2023-12-11T12:32:29.881Z] (main:283440) <INFO> Initializing user accounts manager account store...
[2023-12-11T12:32:29.995Z] (main:283440) <ERRO> IdentityUserAccountsManager._initAccountStore failed to finish: Error: Hub Controller process exited prematurely with exit code 131.
      at ControllerConnection.onControllerProcessExited (/home/andre/Applications/storage-explorer/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:134:21)
      at ChildProcess.<anonymous> (/home/andre/Applications/storage-explorer/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:88:76)
      at Object.onceWrapper (node:events:628:26)
      at ChildProcess.emit (node:events:525:35)
      at Process.onexit (node:internal/child_process:291:12) {
    exitCode: 131
  }
[2023-12-11T12:32:30.000Z] (main:283440) <ERRO> UNHANDLED PROMISE REJECTION in main process:
  Error: Hub Controller process exited prematurely with exit code 131.
[2023-12-11T12:34:23.288Z] (main:283440) <INFO> Calling handleQuitOrRelaunch from quit
[2023-12-11T12:34:23.289Z] (main:283440) <INFO> Quitting, sessionEnded: false, force: true, quitOrRelaunch: quit
[2023-12-11T12:34:23.291Z] (main:283440) <INFO> Calling quit, bye!
```

**Comment by adiroiban** [comment]
I got the same error with Ubuntu 22.04 and the tar version.

The snap version works.

**Comment by TuxmAL** [comment]
Same error here with openSUSE Tumbleweed with the tar version..
