### ISSUE TITLE
Error downloading file (integrity check failed)

### ISSUE THREAD

**Issue by VitoMaltese** [Microsoft/AzureStorageExplorer#800]
```json
{
  "name": "Error",
  "message": "Hash mismatch (integrity check failed), Expected value is MeMHjE3/P6SHzRsRfmXO+w==, retrieved V0Ygt/6H8tMW0jKxFmK0Tg==.",
  "stack": "Error: Hash mismatch (integrity check failed), Expected value is MeMHjE3/P6SHzRsRfmXO+w==, retrieved V0Ygt/6H8tMW0jKxFmK0Tg==.\n    at Object.BlobService._validateLengthAndMD5 (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\services\\blob\\blobservice.core.js:5429:28)\n    at processResponseCallback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\services\\blob\\blobservice.core.js:1877:12)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:327:13)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)"
}
```

**Comment by jinglouMSFT** [comment]
The error indicated that the MD5 check failed.  It's possible the file was corrupted.  Have you tried to re-download the file?

**Comment by craxal** [comment]
Bug getting stale, so I'm closing. If issue persists on latest available version, we can investigate if repro steps are provided.
