### ISSUE TITLE
Immediately after disk copy Connect Timeout Error

### ISSUE THREAD

**Issue by CryptoBlocks-pro** [microsoft/AzureStorageExplorer#8018]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

x64

### Storage Explorer Build Number

20240523.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

With 2 different hard disks, they proceed to copy normally. They hit 99% complete, then after some number of seconds fail with this error:
Storage Explorer was unable to revoke access to a disk.
The disks involved in this operation may still be in an 'Active SAS' or 'Active Upload' state. You may need to return the disks to an 'Unattached' state before retrying this operation, or before performing new operations on the disks.

Service response: {
  "name": "Node Fetch Error",
  "message": "Connect Timeout Error",
  "stack": "ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (C:\\Users\\erlong\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:36240)\n    at C:\\Users\\erlong\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:35582\n    at Immediate._onImmediate (C:\\Users\\erlong\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:35945)\n    at process.processImmediate (node:internal/timers:478:21)",
  "cause": {
    "cause": {
      "name": "ConnectTimeoutError",
      "code": "UND_ERR_CONNECT_TIMEOUT"
    }
  },
  "code": "UND_ERR_CONNECT_TIMEOUT"
}

Storage Explorer was unable to revoke access to a disk.
The disks involved in this operation may still be in an 'Active SAS' or 'Active Upload' state. You may need to return the disks to an 'Unattached' state before retrying this operation, or before performing new operations on the disks.

Service response: {
  "name": "Node Fetch Error",
  "message": "Connect Timeout Error",
  "stack": "ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (C:\\Users\\erlong\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:36240)\n    at C:\\Users\\erlong\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:35582\n    at Immediate._onImmediate (C:\\Users\\erlong\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:35945)\n    at process.processImmediate (node:internal/timers:478:21)",
  "cause": {
    "cause": {
      "name": "ConnectTimeoutError",
      "code": "UND_ERR_CONNECT_TIMEOUT"
    }
  },
  "code": "UND_ERR_CONNECT_TIMEOUT"
}

Disk state still shows ActiveUpload for both disks.

### Steps to Reproduce

Copy a source disk. Paste a disk into destination. Watch progress in Activities section.

### Actual Experience

after progress gets to 99%, a timeout error occurs. The second time this happened I was actively clicking between resource groups in the explorer to view disks, trying to ensure that the underlying Azure connection was not timing out. 

After the first 500 GB disk exhibited this, I did have to re-authenticate with Azure. The second time, with 256 GB disk, it did not need to be re-authenticated, I can still browse through the resource groups and see disks.

### Expected Experience

Copy/Past progresses to 100% and completes successfully.

**Comment by CryptoBlocks-pro** [comment]
I can recover and use the disks by using this command:
Revoke-AzDiskAccess -ResourceGroupName '<RG_Name>' -DiskName '<Disk_Name>'

**Comment by craxal** [comment]
Does this reproduce 100% of the time? Or does this reproduce only for certain disks or for certain network configurations?

Does the disk copy appear to be complete minus the access revoke? Does the `Revoke-AzDiskAccess` command definitely unblock you?
