### ISSUE TITLE
Reauthentication loop when using users from trusted domain

### ISSUE THREAD

**Issue by MartinDrue** [microsoft/AzureStorageExplorer#8050]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

x64

### Platform

Windows

### OS Version

Server 2022

### Bug Description

We are experiencing a weird bug with Storage Explorer. The scenario is as following: 

Storage Explorer runs on a server in Domain A (Resource Domain)
Users log in to the server with an identity from Domain B (Identity Forest) that is synced to Entra ID

When using this case, Authentication to Storage Explorer fails and the user is required to reauthenticate (which again doesn't work). 
This is reproducable on different users on the same server. 
Using a local user account on the server, authentication works fine. 

Error message in SE logs: 
```
Failed to get AAD Organizations during account creation because of 'Microsoft.Developer.IdentityService.AccountProvider.NoMatchingAccountException: No matching accounts found in any MSAL cache.
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(String resource, String tenant, UserIdentifier userId, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken)
   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderNetworkServicesBase.AcquireGraphTokenAsync(String resource, AuthenticationInfo userInfo, String tenantId, Boolean promptIfNeeded, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, CancellationToken ct)
   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderNetworkServicesBase.GetAADOrganizationInformationAsync(AuthenticationInfo authInfo, Boolean promptIfNeeded, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, CancellationToken cancellationToken)
   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderNetworkServicesBase.GetAADOrganizationInformationAsync(AuthenticationInfo authInfo, Boolean promptIfNeeded, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, CancellationToken cancellationToken)
   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.GetAADOrganizationsInfoAsync(AuthenticationInfo authInfo, Boolean promptIfNeeded, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, CancellationToken cancellationToken)
   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.CreateAccountFromAadAsync(Account account, ImmutableArray`1 scopes, List`1 errors, AuthenticationInfo authInfo, Boolean promptIfNeeded, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, CancellationToken cancellationToken)'

```
We've tried to change authentication methods, but none of the offered solutions work. Using different Entra ID accounts does not change the outcome. 
Adding Storage Accounts using SAS Token works fine, but is not the targeted solution. 

### Steps to Reproduce

1. Login to Server using an account from trusted domain
2. Start Storage Explorer
3. Authentication using Entra ID
4. Authentication is marked as successful but user is required to reauthenticate

### Actual Experience

1. User tries to authenticate to Entra ID 
2. Browser opens for authentication, users authenticated successfully
3. After authentication, several browser tabs open
4. Authentication is marked as complete in Storage Explorer
5. User is asked to reauthenticate, Error Message "No matching accounts found in any MSAL cache."

**Comment by craxal** [comment]
Possible duplicate of #8029.

**Comment by MartinDrue** [comment]
Issue fixed, was a configuration issue on the server: 
We had to create a DWORD Regkey "ProtectionPolicy" set to 1 in Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Protect\Providers\df9d8cd0-1501-11d1-8c7a-00c04fc297eb

Not sure why this wasn't set before. Closing Issue
