### ISSUE TITLE
Issue when trying to use WAM/authentication broker on Windows

### ISSUE THREAD

**Issue by samnaliev** [microsoft/AzureStorageExplorer#8237]
Hi.
The issue came out of the blue (or at least it seems like)
When I try to authenticate to Azure in order to access my storage accounts, I'm getting the following error:

```json
{
  "message": "\"Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details\""
}
```

Can you please advice

I even reinstalled the app, but nothing helped

**Comment by muskad202** [comment]
I am hitting the same error. The Reset option did not help.
Version 1.36.0 (101)

**Comment by samnaliev** [comment]
@MRayermannMSFT 

It was the sign-in method.
It started working again after I changed it to 'default browser'.
Thanks.

**Comment by JasonYeMSFT** [comment]
If you are still able to reproduce the issue, could you please do us a favor to turn on the verbose logging, collect the authentication logs and share the logs with us? The logs may help us locate the cause of the issue and make a fix.

There are detailed instructions in this section of our troubleshooting guide
https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs

**Comment by craxal** [comment]
Due to how widespread this issue is, we will be releasing 1.36.2 very soon to revert the default authentication method for Windows users.

For anyone having this issue, we invite you to do the following:

## Help us diagnose

1. Install Storage Explorer 1.36.x.
2. Ensure you are signed out and that the "Sign in with:" setting is set to "Authentication Broker".
3. Follow the [troubleshooting docs](https://learn.microsoft.com/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs) to gather authentication logs.
4. Please clear out any existing logs from the logs folder if you can.
5. Share your logs here!

## Unblock yourself

1. Install Storage Explorer 1.36.x.
2. Change the value for the "Sign In with:" setting to be "Default Web Browser".
3. Try signing in.

Thank you everyone for your patience and your help in diagnosing this issue!

**Comment by simonfox** [comment]
Quite a few log files generated, this one looks most relevant...

```
10/29/2024 09:43:08 New Zealand Standard Time : Information : Local timezone is (UTC+12:00) Auckland, Wellington
10/29/2024 09:43:08 New Zealand Standard Time : Information : DefaultInstance | Environment variable VS_USE_DEFAULTPROXY found: False
10/29/2024 09:43:08 New Zealand Standard Time : Information : DefaultInstance | Credentials used DefaultCredentials
10/29/2024 09:43:08 New Zealand Standard Time : Information : DefaultInstance | StaticNetworkClientFactory type NoProxy
10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccountProviderService::ctor | StaticNetworkClientFactory Type: NoProxy
10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccountProviderService::ctor (2) | StaticNetworkClientFactory type: NoProxy
10/29/2024 09:43:08 New Zealand Standard Time : Information : Creating 'AadAccountProviderService''
10/29/2024 09:43:08 New Zealand Standard Time : Information : Network services is null? 'True'
10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccount Provider service module Created
10/29/2024 09:43:08 New Zealand Standard Time : Information : Created 'SessionTokenFileStore' at location 'C:\Users\adm.sfox\AppData\Local\.IdentityService\SessionTokens.json'
10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccountProviderService read: Content-Length: 891


10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccountProviderService read: {"jsonrpc":"2.0","id":0,"method":"InitializeAsync","params":[{"AuthenticationQueryParameters":"","AsmEndPoint":"https://management.core.windows.net/","Authority":"https://login.microsoftonline.com/","AzureResourceManagementEndpoint":"https://management.azure.com/","AzureResourceManagementAudienceEndpoints":["https://management.core.windows.net/"],"ClientIdentifier":"e0001ebd-e920-49b8-a27e-92e573ec0af6","EnvironmentName":"AzureCloud","GraphEndpoint":"https://graph.windows.net/","MsaHomeTenantId":"f8cdef31-a31e-4b4a-93e4-5f571e91255a","NativeClientRedirect":"https://login.microsoftonline.com/common/oauth2/nativeclient","PortalEndpoint":"https://portal.azure.com/","ResourceEndpoint":"https://management.core.windows.net/","ValidateAuthority":true,"VisualStudioOnlineAudience":"499b84ac-1321-427f-aa17-267ca6975798","VisualStudioOnlineEndpoint":"https://app.vssps.visualstudio.com/"}]}
10/29/2024 09:43:08 New Zealand Standard Time : Information : Starting to initialize  'InitializeAsync'
10/29/2024 09:43:08 New Zealand Standard Time : Information : Setting 'MsalNetworkServicesImpl', Is  it null 'True'
10/29/2024 09:43:08 New Zealand Standard Time : Information : DefaultInstance | Environment variable VS_USE_DEFAULTPROXY found: False
10/29/2024 09:43:08 New Zealand Standard Time : Information : DefaultInstance | Credentials used DefaultCredentials
10/29/2024 09:43:08 New Zealand Standard Time : Information : DefaultInstance | StaticNetworkClientFactory type NoProxy
10/29/2024 09:43:08 New Zealand Standard Time : Information : HttpClientWrapper::ctor | StaticNetworkClientFactory Type: NoProxy
10/29/2024 09:43:08 New Zealand Standard Time : Information : Completed base constructor of 'AadAccountProviderNetworkServicesBase'
10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccountProviderNetworkServicesBase::ctor (2) | StaticNetworkClientFactory type: NoProxy
10/29/2024 09:43:08 New Zealand Standard Time : Information : Completed initialization of 'InitializeAsync'
10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccountProviderService write: Content-Length: 38

{"jsonrpc":"2.0","id":0,"result":null}
10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccountProviderService read: Content-Length: 85


10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccountProviderService read: {"jsonrpc":"2.0","id":1,"method":"SetAdditionalContextPropertiesAsync","params":[{}]}
10/29/2024 09:43:08 New Zealand Standard Time : Information : AadAccountProviderService write: Content-Length: 38

{"jsonrpc":"2.0","id":1,"result":null}
10/29/2024 09:43:19 New Zealand Standard Time : Information : AadAccountProviderService read: Content-Length: 203


10/29/2024 09:43:19 New Zealand Standard Time : Information : AadAccountProviderService read: {"jsonrpc":"2.0","id":2,"method":"CreateAccountAsync","params":[{"QueryString":"site_id=501454&display=popup&nux=1&lc=1033","AuthenticationFlowType":"4","HomeTenantOnly":"true","WindowHandle":"197232"}]}
10/29/2024 09:43:19 New Zealand Standard Time : Information : Tenant is: 'organizations'
10/29/2024 09:43:19 New Zealand Standard Time : Information : IsAuthority ADFS: 'False'
10/29/2024 09:43:19 New Zealand Standard Time : Information : Using User: ''
10/29/2024 09:43:19 New Zealand Standard Time : Information : Using resource: 'https://management.core.windows.net/', tenant:'organizations'
10/29/2024 09:43:19 New Zealand Standard Time : Information : Using scopes: 'https://management.core.windows.net//.default'
10/29/2024 09:43:19 New Zealand Standard Time : Information : Using authority: 'https://login.microsoftonline.com/organizations'
10/29/2024 09:43:19 New Zealand Standard Time : Information : Calling back to the client to determine if it supports UI
10/29/2024 09:43:19 New Zealand Standard Time : Information : AadAccountProviderService write: Content-Length: 63

{"jsonrpc":"2.0","id":2,"method":"SupportsUIAsync","params":[]}
10/29/2024 09:43:19 New Zealand Standard Time : Information : AadAccountProviderService read: Content-Length: 38


10/29/2024 09:43:19 New Zealand Standard Time : Information : AadAccountProviderService read: {"jsonrpc":"2.0","id":2,"result":true}
10/29/2024 09:43:19 New Zealand Standard Time : Information : Client supports UI? 'True'
10/29/2024 09:43:19 New Zealand Standard Time : Information : Going to use interactive flow with authenticationFlowType 'WAM'
10/29/2024 09:43:19 New Zealand Standard Time : Information : GetPublicClient for authority: 'https://login.microsoftonline.com/organizations' ValidateAuthority: 'True'
10/29/2024 09:43:19 New Zealand Standard Time : Information : DefaultInstance | Environment variable VS_USE_DEFAULTPROXY found: False
10/29/2024 09:43:19 New Zealand Standard Time : Information : DefaultInstance | Credentials used DefaultCredentials
10/29/2024 09:43:19 New Zealand Standard Time : Information : DefaultInstance | StaticNetworkClientFactory type NoProxy
10/29/2024 09:43:19 New Zealand Standard Time : Information : MsalNetworkServices::GetPublicClientAsync | StaticNetworkClientFactory Type: NoProxy
10/29/2024 09:43:19 New Zealand Standard Time : Information : Built public client
10/29/2024 09:43:19 New Zealand Standard Time : Information : Cache registered
10/29/2024 09:43:19 New Zealand Standard Time : Information : Going to use WAM flow
10/29/2024 09:43:19 New Zealand Standard Time : Information : DefaultInstance | Environment variable VS_USE_DEFAULTPROXY found: False
10/29/2024 09:43:19 New Zealand Standard Time : Information : DefaultInstance | Credentials used DefaultCredentials
10/29/2024 09:43:19 New Zealand Standard Time : Information : DefaultInstance | StaticNetworkClientFactory type NoProxy
10/29/2024 09:43:19 New Zealand Standard Time : Information : ExecuteWAMFlowAsync | StaticNetworkClientFactory Type: NoProxy
10/29/2024 09:43:20 New Zealand Standard Time : Error : ******START MSAL DIAGNOSTICS******
True MSAL 4.61.3.0 MSAL.NetCore .NET 8.0.8 Microsoft Windows 10.0.14393 [2024-10-28 20:43:20Z - 005a8c05-29a1-4a8c-8a98-5c1efd4c8cc3] MSAL.NetCore.4.61.3.0.MsalClientException:
	ErrorCode: loopback_redirect_uri
Microsoft.Identity.Client.MsalClientException: Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.UpdateRedirectUri(Uri redirectUri)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)

******END MSAL DIAGNOSTICS******
10/29/2024 09:43:20 New Zealand Standard Time : Error : There was a problem executing interactive flow error: 'MSAL.NetCore.4.61.3.0.MsalClientException:
	ErrorCode: loopback_redirect_uri
Microsoft.Identity.Client.MsalClientException: Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.UpdateRedirectUri(Uri redirectUri)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteWAMFlowAsync(MsalGetTokenInteractiveContext context, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 943
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.DoWAMFlowAsync(MsalGetTokenInteractiveContext context, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 578
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteInteractiveFlowAsync(IGetTokenInteractiveContext getTokenContext, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 435'
10/29/2024 09:43:20 New Zealand Standard Time : Error : ******START MSAL DIAGNOSTICS******

******END MSAL DIAGNOSTICS******
10/29/2024 09:43:20 New Zealand Standard Time : Error : There was a problem getting the access token using the prompt with UI flow. Error: 'MSAL.NetCore.4.61.3.0.MsalClientException:
	ErrorCode: loopback_redirect_uri
Microsoft.Identity.Client.MsalClientException: Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.UpdateRedirectUri(Uri redirectUri)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteWAMFlowAsync(MsalGetTokenInteractiveContext context, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 943
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.DoWAMFlowAsync(MsalGetTokenInteractiveContext context, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 578
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteInteractiveFlowAsync(IGetTokenInteractiveContext getTokenContext, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 435
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteInteractiveFlowAsync(IGetTokenInteractiveContext getTokenContext, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 483
   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderNetworkServicesBase.AcquireTokenWithPromptInternalAsync(String resource, String tenant, UserIdentifier userId, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\AadAccountProviderNetworkServicesBase.cs:line 876'
10/29/2024 09:43:20 New Zealand Standard Time : Error : CreateAccount: Creating an account. QueryParameters 'site_id=501454&display=popup&nux=1&lc=1033'
Account creation failed. 
Error: 'MSAL.NetCore.4.61.3.0.MsalClientException:
	ErrorCode: loopback_redirect_uri
Microsoft.Identity.Client.MsalClientException: Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.UpdateRedirectUri(Uri redirectUri)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteWAMFlowAsync(MsalGetTokenInteractiveContext context, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 943
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.DoWAMFlowAsync(MsalGetTokenInteractiveContext context, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 578
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteInteractiveFlowAsync(IGetTokenInteractiveContext getTokenContext, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 435
   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteInteractiveFlowAsync(IGetTokenInteractiveContext getTokenContext, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\MsalNetworkServicesImpl.cs:line 483
   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderNetworkServicesBase.AcquireTokenWithPromptInternalAsync(String resource, String tenant, UserIdentifier userId, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\AadAccountProviderNetworkServicesBase.cs:line 876
   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.CreateAccountInnerAsync(String userName, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, Boolean homeTenantOnly, CancellationToken cancellationToken) in D:\a\_work\1\s\src\IdentityService\Microsoft.Developer.IdentityService\AccountProvider\AADAccountProvider\AadAccountProviderService.cs:line 889'

10/29/2024 09:43:20 New Zealand Standard Time : Information : AadAccountProviderService write: Content-Length: 5308


10/29/2024 09:43:20 New Zealand Standard Time : Information : AadAccountProviderService write: {"jsonrpc":"2.0","id":2,"result":{"UserCancelled":false,"Errors":[{"Message":"Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details","ExceptionType":"Microsoft.Identity.Client.MsalClientException","HResult":-2146233088,"ExceptionString":"MSAL.NetCore.4.61.3.0.MsalClientException:\r\n\tErrorCode: loopback_redirect_uri\r\nMicrosoft.Identity.Client.MsalClientException: Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details\r\n   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.UpdateRedirectUri(Uri redirectUri)\r\n   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)\r\n   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)\r\n   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteWAMFlowAsync(MsalGetTokenInteractiveContext context, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\MsalNetworkServicesImpl.cs:line 943\r\n   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.DoWAMFlowAsync(MsalGetTokenInteractiveContext context, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\MsalNetworkServicesImpl.cs:line 578\r\n   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteInteractiveFlowAsync(IGetTokenInteractiveContext getTokenContext, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\MsalNetworkServicesImpl.cs:line 435\r\n   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteInteractiveFlowAsync(IGetTokenInteractiveContext getTokenContext, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\MsalNetworkServicesImpl.cs:line 483\r\n   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderNetworkServicesBase.AcquireTokenWithPromptInternalAsync(String resource, String tenant, UserIdentifier userId, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\AadAccountProviderNetworkServicesBase.cs:line 876\r\n   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.CreateAccountInnerAsync(String userName, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, Boolean homeTenantOnly, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\AadAccountProviderService.cs:line 889","Data":{"FaultEventCorrelationId":"{\"id\":\"3d1c4295-85a9-46de-ac9f-312dc8a32046\",\"eventType\":\"Fault\"}","FaultEventSessionId":"89972e1e-6a55-4f94-908c-0c85818ea547","HelpLinkBaseUrl":" https://aka.ms/ReportAProblemUrl","HelpLink":" https://aka.ms/ReportAProblemUrl","ErrorCode":"Error","ErrorMessage":"Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details","BrokerErrorContext":null,"BrokerErrorStatus":null,"BrokerErrorCode":null,"BrokerTag":null,"ErrorTypeMetadataKey":"Microsoft.Identity.Client.MsalClientException"}}]}}
10/29/2024 09:43:29 New Zealand Standard Time : Information : AadAccountProviderService read: end of stream
10/29/2024 09:43:29 New Zealand Standard Time : Information : 1We are disconnecting from the rpc. Reason: RemotePartyTerminated, Description: Reached end of stream.
10/29/2024 09:43:29 New Zealand Standard Time : Information : Checking if 'AadAccountProviderService' implements Microsoft.VisualStudio.Threading.IAsyncDisposable.
10/29/2024 09:43:29 New Zealand Standard Time : Information : Checking if 'AadAccountProviderService' implements System.IAsyncDisposable.
10/29/2024 09:43:29 New Zealand Standard Time : Information : Checking if 'AadAccountProviderService' implements System.IDisposable.
10/29/2024 09:43:29 New Zealand Standard Time : Information : Finishing shutting down service: AadAccountProviderService.

```

**Comment by MRayermannMSFT** [comment]
@simonfox thank you for sharing those logs. Do you know, are you signing into the Azure environment, some other built-in environment, or a custom environment?

Or in other words, which of these are you picking?
![Image](https://github.com/user-attachments/assets/addcc516-098d-4717-aa35-46fa7aff113c)

**Comment by simonfox** [comment]
@MRayermannMSFT Azure. See my comment on duplicate issue [here](https://github.com/microsoft/AzureStorageExplorer/issues/8247#issuecomment-2425554412)

**Comment by MRayermannMSFT** [comment]
Hello to @ashwin-kambli, @illbegood73, @jiahe620, @kbhosarekar, @Liandrel, @muskad202, @samnaliev, @simonfox, @SSG11082, and @sumo6161 .

I believe all of you are folks who had issues with Storage Explorer 1.36.0 and/or 1.36.1 trying to use authentication broker (also known as WAM) sign in on Windows. Assuming that belief is true, I have a request which would be great if y'all had time for in the next week or so.

We've made fixes for the issues y'all ran into, and we'd like to get your feedback on those fixes. To do so, you need to:

1. Download the Storage Explorer 1.37.0 Preview 1 from here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.37.0-preview.1
1. Install and launch Storage Explorer
1. Go to Settings (gear icon on the left) > "Application" > "Sign-In"
   1. Find "Sign in with" and change to "Authentication Broker"
   1. Find "Verbose Authentication Logging" and check the checkbox
1. Close Storage Explorer
1. Delete the contents of `C:\Users\<your username>\AppData\Local\Temp\servicehub\logs`
1. Start Storage Explorer
1. If needed, reauthenticate. **Please let us know if you cannot reauthenticate (assuming you need to)**
1. Remove your Azure account
1. Restart Storage Explorer
1. Add your Azure account **Please let us know if you cannot add your Azure account**

If you fail to reauthenticate or add back your Azure account, please let us know and share:
1. What error you see in Storage Explorer
1. The files in `C:\Users\<your username>\AppData\Local\Temp\servicehub\logs`

After you are done with this, we recommend you return back to Storage Explorer 1.36, which you can find here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.36.2 . In that version you will likely need to change back to whatever value of "Sign in with" you had previously.

Thank you in advance to everyone who is able to find the time for this!

**Comment by simonfox** [comment]
@MRayermannMSFT can confirm that build has resolved the issue for me.

**Comment by MRayermannMSFT** [comment]
The preview release has been un-published. You can now use 1.37.0: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.37.0
