### ISSUE TITLE
Cannot connect to ASE

### ISSUE THREAD

**Issue by nisjohn898** [microsoft/AzureStorageExplorer#8335]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.14.2

### Architecture

i86

### Platform

All

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"Failed to refresh access token\\\",\\n  \\\"stack\\\": \\\"Error: Failed to refresh access token\\\\n    at PathClient.<anonymous> (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\se-adls2-extension\\\\\\\\dist\\\\\\\\src\\\\\\\\Clients\\\\\\\\StorageClient.js:227:35)\\\\n    at step (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:141:27)\\\\n    at Object.next (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:122:57)\\\\n    at fulfilled (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:112:62)\\\\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\\\"\\n}\""
}

### Steps to Reproduce

Launch Storage Explorer 

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"Failed to refresh access token\\\",\\n  \\\"stack\\\": \\\"Error: Failed to refresh access token\\\\n    at PathClient.<anonymous> (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\se-adls2-extension\\\\\\\\dist\\\\\\\\src\\\\\\\\Clients\\\\\\\\StorageClient.js:227:35)\\\\n    at step (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:141:27)\\\\n    at Object.next (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:122:57)\\\\n    at fulfilled (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:112:62)\\\\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\\\"\\n}\""
}

### Actual Experience

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"Failed to refresh access token\\\",\\n  \\\"stack\\\": \\\"Error: Failed to refresh access token\\\\n    at PathClient.<anonymous> (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\se-adls2-extension\\\\\\\\dist\\\\\\\\src\\\\\\\\Clients\\\\\\\\StorageClient.js:227:35)\\\\n    at step (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:141:27)\\\\n    at Object.next (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:122:57)\\\\n    at fulfilled (C:\\\\\\\\Users\\\\\\\\nisjohn\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:112:62)\\\\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\\\"\\n}\""
}

**Comment by richardMSFT** [comment]
@nisjohn898 We no longer support 32-bit (i86) Storage Explorer. Is it possible for you to install the latest 64-bit version and try again?

**Comment by nisjohn898** [comment]
@***@***.***>

Can you please let me know how I can download the 64 bit version ?

Thanks
Nisha

________________________________

**Comment by richardMSFT** [comment]
Our releases can be found here: https://azure.microsoft.com/en-us/products/storage/storage-explorer#Download-4 or https://github.com/microsoft/AzureStorageExplorer/releases
