### ISSUE TITLE
Issue connecting Azure Storage Explorer

### ISSUE THREAD

**Issue by ashokkumar-anandaraj** [microsoft/AzureStorageExplorer#8389]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Architecture

x64

### Platform

Windows

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\\\\n    at TLSSocket.emit (events.js:315:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\\\\n    at TLSSocket.emit (events.js:315:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Actual Experience

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\\\\n    at TLSSocket.emit (events.js:315:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

**Comment by craxal** [comment]
@ashokkumar-anandaraj You are using a very old version of Storage Explorer. Can you update to the [latest version](https://github.com/microsoft/AzureStorageExplorer/releases) and try again? If the problem persists, please provide the steps you followed that led up to the problem.

**Comment by craxal** [comment]
@ashokkumar-anandaraj @mudassir-jmi If you are using custom certificates, those steps should not be necessary. Did you [add the certificates in Storage Explorer](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#ssl-certificate-issues)?

![Image](https://github.com/user-attachments/assets/65b846d1-01c2-4eae-89fa-bcbf7f68742b)

**Comment by craxal** [comment]
Closing due to inactivity. If this is still an issue, please respond with answers to the above questions any additional details, and we will revisit.
